//! Carried over from heretic-mnemoria
//! `mnemoria-server/ee/ml/crates/ml-engine-ggml-sys/src/lib.rs` at `a160f8c`
//! (the project is closed; this copy is ours now). Cut: the whisper.cpp pin
//! leg. Changed: the pin string names llama.cpp and ggml only, and the
//! native build's backends directory is exported as [`BACKENDS_DIR`].
//!
//! `wipemark-llama-sys` — llama.cpp's build and its raw bindings, and
//! nothing about this product.
//!
//! One shared `ggml` with its backends as run-time-loaded libraries, and
//! `libllama` linked against it. See `PIN.md` for the pinned commit, the
//! prebuilt release, their evidence and the bump procedure.
//!
//! ## Build modes
//!
//! - default: no C++ is compiled, the bindings are absent and
//!   [`BUILT_NATIVE`] is `false`. A plain `cargo check` needs no cmake, no
//!   libclang, no download and no fetched `vendor/` tree.
//! - `--features native`: build.rs links llama.cpp at the pin — the
//!   prebuilt release of `GigLaboCom/llama-cpp-prebuilt` for the target by
//!   default ([`PREBUILT`]), an unpacked archive named by
//!   `WIPEMARK_LLAMA_PREBUILT`, or, with `WIPEMARK_LLAMA_SOURCE=1` or on a
//!   target nobody publishes, a cmake build of the fetched tree with
//!   bindgen — and the bindings are re-exported from this crate's root.
//!
//! No hand-written `unsafe` lives here: every call site is in
//! `wipemark_llama::ffi`.

#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]

/// Whether this build linked the real ggml and llama.cpp libraries.
///
/// `false` for the default (shim) build, `true` under `--features native`.
/// The safe layer reads it to refuse by name rather than fail to link.
pub const BUILT_NATIVE: bool = cfg!(wipemark_llama_native);

/// Where the native build's ggml backend libraries are — the prebuilt
/// archive's `backends/`, or `$OUT_DIR/backends` of a source build: the
/// development default `Runtime::init` loads from. `None` in a shim build,
/// which has no backends at all.
#[cfg(wipemark_llama_native)]
pub const BACKENDS_DIR: Option<&str> = Some(env!("WIPEMARK_LLAMA_BACKENDS_DIR"));
/// Where the native build installed the ggml backend libraries. `None` in
/// a shim build, which has no backends at all.
#[cfg(not(wipemark_llama_native))]
pub const BACKENDS_DIR: Option<&str> = None;

/// Whether the linked llama.cpp is the prebuilt archive (`true`) or was
/// built from source here (`false`, and in a shim build).
pub const PREBUILT: bool = cfg!(wipemark_llama_prebuilt);

/// The llama.cpp this crate links, the ggml it vendors, and the prebuilt
/// release of it with the sha256 of every archive.
///
/// The same file is compiled into `build.rs`, which verifies a prebuilt
/// archive against it; `PIN.md` and `vendor/fetch.sh` are kept identical to
/// it, and the tests below keep the pieces consistent with one another.
pub mod pin;

// FFI bindings: `$OUT_DIR/bindings.rs`, written by build.rs only under
// `--features native` (which is also when it sets `wipemark_llama_native`)
// — generated by bindgen in a source build, copied from the archive in a
// prebuilt one.
#[cfg(wipemark_llama_native)]
#[allow(
    clippy::all,
    clippy::pedantic,
    unused_qualifications,
    missing_debug_implementations,
    improper_ctypes
)]
mod bindings {
    include!(concat!(env!("OUT_DIR"), "/bindings.rs"));
}

#[cfg(wipemark_llama_native)]
pub use bindings::*;

#[cfg(test)]
mod tests {
    use super::pin;

    #[test]
    fn the_pin_names_its_llama_commit_and_ggml_version() {
        assert!(
            pin::LLAMA_COMMIT.starts_with(pin::LLAMA_SHORT) && pin::LLAMA_SHORT.len() == 7,
            "LLAMA_SHORT {} is not the first seven characters of LLAMA_COMMIT {}",
            pin::LLAMA_SHORT,
            pin::LLAMA_COMMIT
        );
        assert_eq!(
            pin::PIN,
            format!("ggml-{}+llama-{}", pin::GGML_VERSION, pin::LLAMA_SHORT),
            "PIN is not built from GGML_VERSION and LLAMA_SHORT"
        );
    }

    /// The pin is one file, `src/pin.rs`, which `build.rs` compiles too;
    /// `PIN.md` and `vendor/fetch.sh` are copies. A bump that misses one
    /// fetches a tree `build.rs` refuses, or leaves a document describing
    /// libraries nobody links.
    #[test]
    fn every_copy_of_the_pin_agrees() {
        let fetch = include_str!("../vendor/fetch.sh");
        assert!(
            fetch.contains(&format!("LLAMA_COMMIT=\"{}\"", pin::LLAMA_COMMIT)),
            "vendor/fetch.sh fetches another commit than {}",
            pin::LLAMA_COMMIT
        );
        let build = include_str!("../build.rs");
        assert!(
            build.contains("#[path = \"src/pin.rs\"]"),
            "build.rs no longer reads the pin from src/pin.rs"
        );
        assert!(
            !build.contains(pin::LLAMA_COMMIT),
            "build.rs holds a copy of the commit; it reads src/pin.rs instead"
        );
        let doc = include_str!("../PIN.md");
        for needle in [
            pin::LLAMA_COMMIT,
            pin::GGML_COMMIT,
            pin::PIN,
            pin::LLAMA_TAG,
            pin::PREBUILT_REPO,
            &format!("releases/tag/{}", pin::PREBUILT_TAG),
        ] {
            assert!(doc.contains(needle), "PIN.md does not name {needle}");
        }
        for (target, sha256) in pin::PREBUILT_SHA256 {
            assert!(
                doc.lines()
                    .any(|line| line.contains(target) && line.contains(sha256)),
                "PIN.md has no line naming {target} with its archive's sha256 {sha256}"
            );
        }
        assert!(
            pin::LLAMA_TAG.starts_with('b') && pin::LLAMA_TAG[1..].parse::<u32>().is_ok(),
            "{} is not a llama.cpp release tag",
            pin::LLAMA_TAG
        );
    }

    /// Four targets, each with a full sha256, and a release that carries the
    /// pinned tag — the producer tags a release with the llama.cpp tag it
    /// builds, and a re-release may only add a suffix.
    #[test]
    fn the_prebuilt_pin_is_four_targets_of_full_sha256() {
        assert!(
            pin::PREBUILT_TAG == pin::LLAMA_TAG
                || pin::PREBUILT_TAG.starts_with(&format!("{}-", pin::LLAMA_TAG)),
            "the prebuilt release {} is not of the pinned tag {}",
            pin::PREBUILT_TAG,
            pin::LLAMA_TAG
        );
        let mut targets: Vec<&str> = pin::PREBUILT_SHA256.iter().map(|(t, _)| *t).collect();
        targets.sort_unstable();
        targets.dedup();
        assert_eq!(targets.len(), pin::PREBUILT_SHA256.len(), "a target twice");
        for (target, sha256) in pin::PREBUILT_SHA256 {
            assert_eq!(sha256.len(), 64, "{target}: {sha256} is not a sha256");
            assert!(
                sha256
                    .chars()
                    .all(|c| c.is_ascii_hexdigit() && !c.is_ascii_uppercase()),
                "{target}: {sha256} is not lower-case hexadecimal"
            );
            assert_eq!(pin::prebuilt_sha256(target), Some(sha256));
        }
        assert_eq!(pin::prebuilt_sha256("riscv64gc-unknown-linux-gnu"), None);
        assert_eq!(
            pin::prebuilt_url("x86_64-unknown-linux-gnu"),
            format!(
                "https://github.com/GigLaboCom/llama-cpp-prebuilt/releases/download/{0}/\
                 llama-cpp-{0}-x86_64-unknown-linux-gnu.tar.gz",
                pin::PREBUILT_TAG
            )
        );
    }

    /// A source build on a target the release publishes, with the
    /// release's archive already in the cache, compiles both bindings in:
    /// the two modes must hand `wipemark_llama::ffi` one API. bindgen's
    /// output also depends on the libclang it loaded — another version
    /// words a doc comment or a layout assertion differently — so what is
    /// compared is the code with those left out (`api`), and byte identity
    /// is reported when it holds.
    #[cfg(wipemark_llama_compare_bindings)]
    #[test]
    fn the_archive_bindings_are_the_ones_bindgen_generates() {
        let generated = include_str!(concat!(env!("OUT_DIR"), "/bindings.rs"));
        let archived = include_str!(concat!(env!("OUT_DIR"), "/prebuilt-bindings.rs"));
        if generated.replace("\r\n", "\n") == archived.replace("\r\n", "\n") {
            eprintln!("bindings: byte-identical");
            return;
        }
        let (ours, theirs) = (api(generated), api(archived));
        if let Some(at) = ours
            .bytes()
            .zip(theirs.bytes())
            .position(|(a, b)| a != b)
            .or_else(|| (ours.len() != theirs.len()).then(|| ours.len().min(theirs.len())))
        {
            let around = |s: &str| s[at.saturating_sub(120)..(at + 120).min(s.len())].to_owned();
            panic!(
                "the archive's bindings declare another API than bindgen generates here, \
                 from byte {at} of the whitespace-free code:\n  generated: …{}…\n  archive:   …{}…",
                around(&ours),
                around(&theirs)
            );
        }
        eprintln!("bindings: the same API, not byte-identical (another libclang)");
    }

    /// A bindings file as code: comments, attributes and the
    /// `const _: () = { … };` layout assertions dropped, whitespace removed.
    #[cfg(wipemark_llama_compare_bindings)]
    fn api(bindings: &str) -> String {
        let mut out = String::new();
        let mut in_assertions = false;
        for line in bindings.lines().map(str::trim) {
            if in_assertions {
                in_assertions = line != "};";
                continue;
            }
            if line.starts_with("const _: () = {") {
                in_assertions = true;
                continue;
            }
            if line.starts_with("//") || line.starts_with("#[") || line.starts_with("#![") {
                continue;
            }
            out.extend(line.chars().filter(|c| !c.is_whitespace()));
        }
        out
    }

    #[test]
    fn commit_hashes_are_full_sha1() {
        for sha in [pin::LLAMA_COMMIT, pin::GGML_COMMIT] {
            assert_eq!(sha.len(), 40, "{sha} is not a full 40-character sha1");
            assert!(
                sha.chars()
                    .all(|c| c.is_ascii_hexdigit() && !c.is_ascii_uppercase()),
                "{sha} is not lower-case hexadecimal"
            );
        }
    }
}
