//! The paragraphs `estimate_tokens` was calibrated on, with the token
//! count Qwen3 4B Instruct 2507's own tokenizer gave each one
//! (`llama-server /tokenize`, 2026-10-03, the catalogue's
//! `Qwen3-4B-Instruct-2507-UD-Q4_K_XL.gguf`). A test holds the estimate to
//! them: no paragraph may be undercounted by more than 10 %.

/// `(language, tokens, paragraph)`.
pub(super) const PARAGRAPHS: &[(&str, u32, &str)] = &[
    ("en", 35, "The committee met on Tuesday to review the budget for the coming year. After a long discussion, the members agreed to postpone the decision until the auditors had finished their report."),
    ("en", 45, "Rain had been falling since the early morning, and by noon the river was higher than anyone in the village could remember. The old bridge, built in 1887, groaned under the weight of the water."),
    ("en", 33, "If you want to install the package, first make sure that your compiler is recent enough. Older versions will fail with an error that looks unrelated to the actual problem."),
    ("en", 35, "She opened the letter slowly, as if the words inside might change if she read them too quickly. It was from her brother, who had not written in almost three years."),
    ("en", 32, "Modern databases rarely fail because of a single bug. More often, a series of small configuration mistakes accumulates until one ordinary request pushes the system over the edge."),
    ("en", 36, "The museum's new wing will house a collection of nineteenth-century maps, many of which have never been shown to the public. Curators expect the exhibition to open in the spring."),
    ("en", 36, "I don't think we should rewrite the whole service. It works, the tests pass, and the customers are happy; what we need is better monitoring, not a new architecture."),
    ("en", 31, "Photosynthesis converts light energy into chemical energy, which plants store as sugars. Almost every food chain on Earth depends, directly or indirectly, on this process."),
    ("en", 31, "When the train finally arrived, forty minutes late, the platform was so crowded that nobody could move. A conductor shouted something that was lost in the noise."),
    ("en", 32, "Our quarterly revenue grew by 12% compared with the same period last year, driven mainly by subscriptions in Europe and a strong holiday season in North America."),
    ("en", 39, "The recipe calls for two cups of flour, a pinch of salt, and enough cold water to bring the dough together. Knead it briefly, then let it rest for half an hour."),
    ("en", 29, "Security updates are released on the second Tuesday of every month. Administrators are encouraged to test them on a staging server before rolling them out widely."),
    ("ru", 57, "Комитет собрался во вторник, чтобы рассмотреть бюджет на следующий год. После долгого обсуждения члены комитета согласились отложить решение до тех пор, пока аудиторы не закончат свой отчёт."),
    ("ru", 64, "Дождь шёл с раннего утра, и к полудню река поднялась выше, чем кто-либо в деревне мог припомнить. Старый мост, построенный в 1887 году, стонал под тяжестью воды."),
    ("ru", 55, "Если вы хотите установить пакет, сначала убедитесь, что ваш компилятор достаточно свежий. Старые версии завершатся ошибкой, которая выглядит не связанной с настоящей проблемой."),
    ("ru", 47, "Она медленно открыла письмо, словно слова внутри могли измениться, если читать их слишком быстро. Оно было от брата, который не писал почти три года."),
    ("ru", 57, "Современные базы данных редко падают из-за одной ошибки. Гораздо чаще накапливается череда мелких ошибок в настройках, пока один обычный запрос не переполнит чашу."),
    ("ru", 53, "В новом крыле музея разместится коллекция карт девятнадцатого века, многие из которых никогда не показывали публике. Кураторы рассчитывают открыть выставку весной."),
    ("ru", 52, "Я не думаю, что нам стоит переписывать весь сервис. Он работает, тесты проходят, клиенты довольны; нам нужен лучший мониторинг, а не новая архитектура."),
    ("ru", 60, "Фотосинтез превращает энергию света в химическую энергию, которую растения запасают в виде сахаров. Почти каждая пищевая цепь на Земле прямо или косвенно зависит от этого процесса."),
    ("ru", 64, "Когда поезд наконец прибыл, опоздав на сорок минут, платформа была так переполнена, что никто не мог пошевелиться. Проводник что-то крикнул, но его голос потонул в шуме."),
    ("ru", 63, "Наша квартальная выручка выросла на 12% по сравнению с тем же периодом прошлого года, в основном благодаря подпискам в Европе и удачному праздничному сезону в Северной Америке."),
    ("ru", 52, "По рецепту нужно два стакана муки, щепотка соли и столько холодной воды, чтобы тесто собралось. Коротко вымесите его и дайте отдохнуть полчаса."),
    ("ru", 46, "Обновления безопасности выходят во второй вторник каждого месяца. Администраторам рекомендуется проверять их на тестовом сервере, прежде чем устанавливать повсеместно."),
    ("de", 62, "Der Ausschuss traf sich am Dienstag, um den Haushalt für das kommende Jahr zu prüfen. Nach einer langen Diskussion einigten sich die Mitglieder darauf, die Entscheidung zu verschieben, bis die Prüfer ihren Bericht abgeschlossen hatten."),
    ("de", 60, "Seit dem frühen Morgen regnete es, und gegen Mittag stand der Fluss höher, als sich irgendjemand im Dorf erinnern konnte. Die alte Brücke, 1887 erbaut, ächzte unter dem Gewicht des Wassers."),
    ("de", 53, "Wenn Sie das Paket installieren möchten, stellen Sie zuerst sicher, dass Ihr Compiler aktuell genug ist. Ältere Versionen brechen mit einer Fehlermeldung ab, die mit dem eigentlichen Problem nichts zu tun zu haben scheint."),
    ("de", 46, "Sie öffnete den Brief langsam, als ob sich die Worte darin ändern könnten, wenn sie sie zu schnell las. Er war von ihrem Bruder, der seit fast drei Jahren nicht geschrieben hatte."),
    ("de", 49, "Moderne Datenbanken fallen selten wegen eines einzelnen Fehlers aus. Häufiger summieren sich kleine Konfigurationsfehler, bis eine ganz gewöhnliche Anfrage das System zum Kippen bringt."),
    ("de", 59, "Im neuen Flügel des Museums wird eine Sammlung von Landkarten aus dem neunzehnten Jahrhundert untergebracht, von denen viele noch nie öffentlich gezeigt wurden. Die Kuratoren erwarten die Eröffnung im Frühjahr."),
    ("de", 55, "Ich glaube nicht, dass wir den ganzen Dienst neu schreiben sollten. Er funktioniert, die Tests laufen durch, und die Kunden sind zufrieden; was wir brauchen, ist besseres Monitoring, keine neue Architektur."),
    ("de", 51, "Die Photosynthese wandelt Lichtenergie in chemische Energie um, die Pflanzen als Zucker speichern. Fast jede Nahrungskette auf der Erde hängt direkt oder indirekt von diesem Vorgang ab."),
    ("de", 50, "Als der Zug endlich mit vierzig Minuten Verspätung eintraf, war der Bahnsteig so voll, dass sich niemand bewegen konnte. Ein Schaffner rief etwas, das im Lärm unterging."),
    ("de", 48, "Unser Quartalsumsatz stieg im Vergleich zum Vorjahreszeitraum um 12 %, vor allem dank Abonnements in Europa und eines starken Weihnachtsgeschäfts in Nordamerika."),
    ("de", 47, "Für das Rezept braucht man zwei Tassen Mehl, eine Prise Salz und so viel kaltes Wasser, dass der Teig zusammenhält. Kurz kneten und dann eine halbe Stunde ruhen lassen."),
    ("de", 48, "Sicherheitsupdates erscheinen am zweiten Dienstag jedes Monats. Administratoren wird empfohlen, sie auf einem Testserver zu prüfen, bevor sie flächendeckend eingespielt werden."),
    ("zh", 29, "委员会于星期二开会，审议来年的预算。经过长时间的讨论，成员们同意推迟决定，直到审计人员完成他们的报告。"),
    ("zh", 42, "雨从清晨一直下个不停，到了中午，河水已经涨到村里没有人记得的高度。那座建于1887年的老桥在水的重压下吱吱作响。"),
    ("zh", 30, "如果你想安装这个软件包，首先要确保你的编译器足够新。旧版本会报出一个看起来与实际问题毫无关系的错误。"),
    ("zh", 30, "她慢慢地打开信，好像读得太快里面的字就会改变似的。信是她哥哥寄来的，他已经将近三年没有写信了。"),
    ("zh", 31, "现代数据库很少因为单个错误而崩溃。更常见的是，一系列小的配置错误不断累积，直到一个普通的请求把系统推向崩溃。"),
    ("zh", 27, "博物馆的新翼将收藏一批十九世纪的地图，其中许多从未向公众展出过。策展人预计展览将在春季开幕。"),
    ("zh", 30, "我不认为我们应该重写整个服务。它运行正常，测试都通过了，客户也很满意；我们需要的是更好的监控，而不是新的架构。"),
    ("zh", 33, "光合作用把光能转化为化学能，植物以糖的形式储存这些能量。地球上几乎每一条食物链都直接或间接地依赖这个过程。"),
    ("zh", 38, "火车终于晚点四十分钟到达时，站台上挤得水泄不通，谁也动弹不得。一位列车员喊了些什么，但声音淹没在嘈杂中。"),
    ("zh", 26, "与去年同期相比，我们的季度收入增长了12%，主要得益于欧洲的订阅业务和北美强劲的假日销售季。"),
    ("ja", 49, "委員会は火曜日に集まり、来年度の予算を検討した。長い議論の末、委員たちは監査人が報告書をまとめるまで決定を延期することで合意した。"),
    ("ja", 50, "雨は早朝から降り続き、昼ごろには川の水位が村の誰も覚えていないほど高くなった。1887年に建てられた古い橋は、水の重みにきしんでいた。"),
    ("ja", 47, "このパッケージをインストールしたい場合は、まずコンパイラが十分に新しいことを確認してください。古いバージョンでは、実際の問題とは無関係に見えるエラーで失敗します。"),
    ("ja", 40, "彼女はゆっくりと手紙を開けた。速く読みすぎると中の言葉が変わってしまうかのように。それは三年近く手紙をよこさなかった兄からのものだった。"),
    ("ja", 54, "現代のデータベースが一つのバグだけで止まることはめったにない。むしろ小さな設定ミスが積み重なり、ありふれた一つのリクエストがシステムを限界の向こうへ押しやるのだ。"),
    ("mixed", 24, "Run ⟦1⟧ before you open ⟦2⟧, otherwise the configuration in ⟦3⟧ is ignored."),
    ("mixed", 21, "See ⟦1⟧ for the details, and write to ⟦2⟧ if something is unclear."),
    ("mixed", 28, "Перед запуском выполните ⟦1⟧ и проверьте файл ⟦2⟧ — без него сервис не стартует."),
    ("mixed", 24, "Siehe ⟦1⟧ für Einzelheiten; die Datei ⟦2⟧ muss vorher existieren."),
    ("mixed", 33, "The function `parse_config()` reads `~/.config/app/settings.toml` and falls back to https://example.com/defaults.json when the file is missing."),
    ("mixed", 21, "- First item of the list\n- Second item, a little longer than the first\n- Third item"),
];
