//! The catalogue gates.
//!
//! A localization bug does not look like a failure. It looks like a
//! window that is 90% German, a label that reads `panel-pending`, a
//! number that is grammatically wrong in a language nobody on the team
//! reads, or a claim that is careful in English and reckless in
//! Russian. None of that stops a build, so all of it is checked here,
//! over every message and every language rather than over the ones
//! someone thought to spot-check.
//!
//! Two of these are product rules rather than i18n hygiene, and they
//! are the ones to delete first when checking that this suite can fail:
//! [`the_third_shelf_is_never_empty_in_any_language`] and
//! [`no_language_promises_more_than_the_product_does`].

use fluent_syntax::{ast, parser};
use unic_langid::LanguageIdentifier;
use wipemark_core::report::not_established;
use wipemark_core::{Confidence, UnicodeClass};

use crate::{
    args, available_languages, catalogue, LanguagePreference, Localizer, Message, Rendering,
    BUILT_LANGUAGES, FALLBACK_LANGUAGE,
};

/// Every shipped language, as ids.
fn languages() -> Vec<LanguageIdentifier> {
    available_languages()
        .iter()
        .map(|language| language.id.clone())
        .collect()
}

/// Arguments for a message, built from the variables its own pattern
/// declares. Generated by `build.rs`, so this cannot drift from the
/// catalogue the way a hand-written table would.
fn arguments(message: Message) -> crate::FluentArgs<'static> {
    let mut args = crate::FluentArgs::new();
    for variable in message.variables() {
        args.set(*variable, "x");
    }
    args
}

/// One language, no fallback behind it — so `defines` is the question
/// "is this translated" rather than "does something render".
fn only(language: &LanguageIdentifier) -> Localizer {
    Localizer::for_languages(std::slice::from_ref(language), Rendering::PlainText)
}

fn parse(source: &str) -> ast::Resource<&str> {
    match parser::parse(source) {
        Ok(resource) => resource,
        Err((_, errors)) => panic!("catalogue does not parse: {errors:?}"),
    }
}

fn message_ids(resource: &ast::Resource<&str>) -> Vec<String> {
    resource
        .body
        .iter()
        .filter_map(|entry| match entry {
            ast::Entry::Message(message) => Some(message.id.name.to_owned()),
            _ => None,
        })
        .collect()
}

// ─── Completeness ────────────────────────────────────────────────────

/// The headline gate: no language, through its own chain, renders a
/// message as its own id.
#[test]
fn every_message_renders_in_every_language() {
    for language in languages() {
        let localizer = Localizer::new(
            &LanguagePreference::Explicit(language.clone()),
            Rendering::PlainText,
        );
        for message in Message::ALL {
            let text = localizer.format_args(message, &arguments(message));
            assert!(
                !text.is_empty() && text != message.id(),
                "{language}: `{}` did not render",
                message.id()
            );
        }
    }
}

/// A *lagging* translation is a supported state — the chain exists for
/// it. A lagging translation that shipped is a review decision, so it
/// fails here, naming every key it is missing.
#[test]
fn shipped_languages_are_complete() {
    for language in languages() {
        let localizer = only(&language);
        let missing: Vec<&str> = Message::ALL
            .iter()
            .filter(|message| !localizer.defines(**message))
            .map(|message| message.id())
            .collect();
        assert!(
            missing.is_empty(),
            "{language} is missing {} of {} messages: {missing:?}",
            missing.len(),
            Message::ALL.len()
        );
    }
}

/// The other direction. A translator's typo produces a key nothing will
/// ever ask for, and the message it was meant to be stays English —
/// which looks exactly like "not translated yet" and is not.
#[test]
fn no_language_defines_a_message_nobody_asks_for() {
    let known: Vec<&str> = Message::ALL.iter().map(|message| message.id()).collect();
    for language in languages() {
        let source = catalogue::source(&language).expect("shipped catalogue");
        let orphans: Vec<String> = message_ids(&parse(&source))
            .into_iter()
            .filter(|id| !known.contains(&id.as_str()))
            .collect();
        assert!(
            orphans.is_empty(),
            "{language} defines keys that are not in the fallback catalogue: {orphans:?}"
        );
    }
}

/// A renamed `$variable` renders perfectly and means something else:
/// the value is dropped and the reader sees a sentence with a hole in
/// it. Compared over the syntax, not the output, because the output is
/// exactly what does *not* show the problem.
#[test]
fn variables_match_the_fallback() {
    let fallback: LanguageIdentifier = FALLBACK_LANGUAGE.parse().expect("fallback tag");
    for language in languages() {
        if language == fallback {
            continue;
        }
        let source = catalogue::source(&language).expect("shipped catalogue");
        let resource = parse(&source);
        for entry in &resource.body {
            let ast::Entry::Message(translated) = entry else {
                continue;
            };
            let Some(message) = Message::ALL
                .iter()
                .find(|message| message.id() == translated.id.name)
            else {
                continue; // covered by no_language_defines_a_message_nobody_asks_for
            };
            let mut found: Vec<String> = Vec::new();
            if let Some(pattern) = &translated.value {
                collect(pattern, &mut found);
            }
            found.sort();
            found.dedup();
            let expected: Vec<String> = message
                .variables()
                .iter()
                .map(|variable| (*variable).to_owned())
                .collect();
            assert_eq!(
                found,
                expected,
                "{language}: `{}` references different variables than en-US",
                message.id()
            );
        }
    }
}

fn collect(pattern: &ast::Pattern<&str>, found: &mut Vec<String>) {
    for element in &pattern.elements {
        if let ast::PatternElement::Placeable { expression } = element {
            collect_expression(expression, found);
        }
    }
}

fn collect_expression(expression: &ast::Expression<&str>, found: &mut Vec<String>) {
    match expression {
        ast::Expression::Inline(ast::InlineExpression::VariableReference { id }) => {
            found.push(id.name.to_owned());
        }
        ast::Expression::Inline(ast::InlineExpression::Placeable { expression }) => {
            collect_expression(expression, found);
        }
        ast::Expression::Inline(_) => {}
        ast::Expression::Select { selector, variants } => {
            if let ast::InlineExpression::VariableReference { id } = selector {
                found.push(id.name.to_owned());
            }
            for variant in variants {
                collect(&variant.value, found);
            }
        }
    }
}

// ─── Product rules ───────────────────────────────────────────────────

/// The third shelf, in every language.
///
/// `wipemark_core::report::not_established` is the list of claims the
/// product refuses to make. A fourth entry added there with no
/// translation would print English inside an otherwise German report —
/// which is the one place in this product where a reader skimming past
/// a paragraph they cannot read is a real cost. Deleting an arm of
/// `not_established::ALL`, or a `report-not-established-*` key from any
/// catalogue, has to turn this red.
#[test]
fn the_third_shelf_is_never_empty_in_any_language() {
    assert!(
        !not_established::ALL.is_empty(),
        "the third shelf is never empty"
    );

    for (id, canonical) in not_established::ALL {
        let key = format!("report-not-established-{id}");
        let message = Message::ALL
            .iter()
            .find(|message| message.id() == key)
            .unwrap_or_else(|| {
                panic!(
                    "`{id}` is on the third shelf but `{key}` is not in the catalogue \
                     (canonical English: {canonical:?})"
                )
            });

        for language in languages() {
            assert!(
                only(&language).defines(*message),
                "{language} has no translation for the third-shelf item `{id}`"
            );
        }
    }
}

/// The picture report's shelf, in every language: its first claim —
/// invisible marks in the pixels, not searched for, not removed — is
/// `wipemark-pixels`'s, and is the one sentence a reader of a cleaned
/// picture most needs. Deleting its key from any catalogue, or adding a
/// claim to the picture shelf with no key, turns this red.
#[test]
fn the_picture_shelf_is_never_empty_in_any_language() {
    let shelf = wipemark_pixels::not_established::shelf();
    assert_eq!(shelf.first(), Some(&wipemark_pixels::not_established::ID));
    for id in shelf {
        let key = format!("report-not-established-{id}");
        let message = Message::ALL
            .iter()
            .find(|message| message.id() == key)
            .unwrap_or_else(|| {
                panic!("`{id}` is on the picture shelf but `{key}` is not in the catalogue")
            });
        for language in languages() {
            assert!(
                only(&language).defines(*message),
                "{language} has no translation for the picture-shelf item `{id}`"
            );
        }
    }
}

/// A vendor or a product of a visible mark is an identifier (Q-V9):
/// interpolated beside a finding, never written into a sentence — a
/// catalogue string that named one would put a trademark into prose and go
/// stale the day the profile is renamed. Every `vendor` and `product` of
/// the compiled-in mark catalogue, in every language, in every message.
#[test]
fn no_catalogue_string_names_a_mark_vendor() {
    let mut names: Vec<String> = Vec::new();
    for key in ["\"vendor\":", "\"product\":"] {
        for (at, _) in wipemark_pixels::EMBEDDED.match_indices(key) {
            let rest = &wipemark_pixels::EMBEDDED[at + key.len()..];
            let Some(open) = rest.find('"') else { continue };
            let value = &rest[open + 1..];
            if let Some(close) = value.find('"') {
                let name = value[..close].to_lowercase();
                if !names.contains(&name) {
                    names.push(name);
                }
            }
        }
    }
    assert!(!names.is_empty(), "the mark catalogue names no vendor");
    for language in languages() {
        let localizer = only(&language);
        for message in Message::ALL {
            let text = localizer
                .format_args(message, &arguments(message))
                .to_lowercase();
            for name in &names {
                let named = text
                    .split(|c: char| !c.is_alphanumeric())
                    .any(|word| word == name);
                assert!(
                    !named,
                    "{language}: `{}` names {name:?} — a vendor is an identifier, \
                     interpolated, never part of a sentence",
                    message.id()
                );
            }
        }
    }
}

/// Every confidence `wipemark_core` has, listed by hand — core has no
/// `Confidence::ALL` — and kept honest by [`confidence_ordinal`]'s
/// exhaustive `match`: a fifth confidence does not compile there until
/// it is added here too.
const CONFIDENCES: [Confidence; 4] = [
    Confidence::LikelyFalsePositive,
    Confidence::Informational,
    Confidence::Probable,
    Confidence::Confirmed,
];

fn confidence_ordinal(confidence: Confidence) -> usize {
    match confidence {
        Confidence::LikelyFalsePositive => 0,
        Confidence::Informational => 1,
        Confidence::Probable => 2,
        Confidence::Confirmed => 3,
    }
}

/// What a finding is and how sure, in every language.
///
/// A report row reads "U+200B ZERO WIDTH SPACE · zero-width character ·
/// confirmed": the name is the standard's and never translated, and the
/// other two are this catalogue's, keyed by the stable ids
/// (`unicode-class-<id>`, `confidence-<id>`). A class added to core with
/// no key, or a key renamed in one catalogue, would print a key — or
/// English inside a German report — in exactly the line a reader needs.
#[test]
fn every_unicode_class_and_confidence_reads_in_every_language() {
    for (index, confidence) in CONFIDENCES.iter().enumerate() {
        assert_eq!(confidence_ordinal(*confidence), index, "{confidence:?}");
    }

    let keys = UnicodeClass::ALL
        .iter()
        .map(|class| format!("unicode-class-{}", class.as_str()))
        .chain(
            CONFIDENCES
                .iter()
                .map(|confidence| format!("confidence-{}", confidence.as_str())),
        );
    for key in keys {
        let message = Message::ALL
            .iter()
            .find(|message| message.id() == key)
            .unwrap_or_else(|| panic!("`{key}` is not in the catalogue"));
        for language in languages() {
            assert!(
                only(&language).defines(*message),
                "{language} has no translation for `{key}`"
            );
        }
    }
}

/// Rule 3 of the honesty contract, held in every language.
///
/// English is reviewed by everyone who reads this repo; a translation
/// is reviewed by whoever wrote it. "Undetectable" is a claim with no
/// oracle behind it — there is no test that could support it — so the
/// gate is on the words rather than on a reviewer's attention.
#[test]
fn no_language_promises_more_than_the_product_does() {
    /// Claims, not vocabulary. `evasion` and `detector` are absent on
    /// purpose: the third shelf says the product does *not* establish
    /// evasion of a vendor's detector, and a gate that banned the noun
    /// would ban the disclaimer.
    const FORBIDDEN: [&str; 12] = [
        // en
        "undetectable",
        "undetected",
        "untraceable",
        "foolproof",
        "guarantee",
        "100%",
        // de
        "unerkennbar",
        "nicht erkennbar",
        "garantiert",
        // ru
        "необнаружим",
        "неопределим",
        "гарантир",
    ];

    for language in languages() {
        let localizer = only(&language);
        for message in Message::ALL {
            let text = localizer
                .format_args(message, &arguments(message))
                .to_lowercase();
            for claim in FORBIDDEN {
                assert!(
                    !text.contains(claim),
                    "{language}: `{}` claims {claim:?} — there is no oracle for that \
                     (spec §0.1 rule 3)",
                    message.id()
                );
            }
        }
    }
}

/// The product's own rule, turned on the product's own strings.
///
/// Layer A removes zero-width characters, bidi controls, soft hyphens
/// and exotic spaces. A catalogue carrying one would put them into
/// every `--json` report and every file the CLI writes, and Wipemark
/// would flag its own output. Fluent's bidi isolation is the way this
/// happens by accident, which is why [`Rendering::PlainText`] exists
/// and why this test formats *with arguments* — the isolation marks
/// only appear around an interpolated value.
#[test]
fn no_message_carries_a_character_layer_a_would_strip() {
    for language in languages() {
        let localizer = only(&language);
        for message in Message::ALL {
            let text = localizer.format_args(message, &arguments(message));
            for (index, character) in text.char_indices() {
                assert!(
                    !stripped_by_layer_a(character),
                    "{language}: `{}` contains U+{:04X} at byte {index} — Layer A removes it",
                    message.id(),
                    character as u32
                );
            }
        }
    }
}

/// The classes `wipemark_core::UnicodeClass` marks for removal, as
/// ranges. Deliberately a second, independent spelling of the table:
/// this suite must not be able to pass because the classifier is wrong.
fn stripped_by_layer_a(character: char) -> bool {
    let code = character as u32;
    matches!(code,
        0x00AD                              // soft hyphen
        | 0x00A0 | 0x2000..=0x200A          // exotic spaces
        | 0x202F | 0x205F | 0x3000
        | 0x200B..=0x200F                   // zero width, ZWJ, LRM/RLM
        | 0x202A..=0x202E | 0x2060          // bidi embedding, word joiner
        | 0x2066..=0x2069                   // bidi isolates — Fluent's own
        | 0xFEFF
        | 0xFE00..=0xFE0F                   // variation selectors
        | 0xFDD0..=0xFDEF                   // noncharacters
        | 0xE000..=0xF8FF                   // private use
        | 0xE0000..=0xE007F                 // tag characters
        | 0xE0100..=0xE01EF
        | 0xF0000..=0xFFFFD
        | 0x100000..=0x10FFFD
    ) || (code & 0xFFFE) == 0xFFFE
}

/// The other half of the same decision. If `Rendering` made no
/// difference, [`no_message_carries_a_character_layer_a_would_strip`]
/// would pass for the wrong reason.
#[test]
fn a_window_isolates_what_a_pipe_must_not() {
    let english: LanguageIdentifier = FALLBACK_LANGUAGE.parse().expect("fallback tag");
    let args = args!("language" => "العربية");

    let ui = Localizer::for_languages(std::slice::from_ref(&english), Rendering::Ui)
        .format_args(Message::LanguageSystem, &args);
    let plain = Localizer::for_languages(std::slice::from_ref(&english), Rendering::PlainText)
        .format_args(Message::LanguageSystem, &args);

    assert!(
        ui.contains('\u{2068}') && ui.contains('\u{2069}'),
        "a window must isolate an interpolated value: {ui:?}"
    );
    assert!(
        !plain.contains('\u{2068}') && !plain.contains('\u{2069}'),
        "a pipe must not carry isolates: {plain:?}"
    );
    assert_eq!(
        ui.replace(['\u{2068}', '\u{2069}'], ""),
        plain,
        "the two renderings must differ only by the isolates"
    );
}

/// A window's localizer still has a road to plain text, per call: the
/// title it hands the platform. Every language, because the twin chain is
/// built per link.
#[test]
fn a_window_can_ask_for_plain_text_per_call() {
    let args = args!("language" => "עברית");
    for language in available_languages() {
        let ui = Localizer::for_languages(std::slice::from_ref(&language.id), Rendering::Ui);
        let isolated = ui.format_args(Message::LanguageSystem, &args);
        let plain = ui.format_args_plain(Message::LanguageSystem, &args);
        assert!(
            isolated.contains('\u{2068}'),
            "{}: {isolated:?}",
            language.id
        );
        assert!(
            !plain.contains(['\u{2068}', '\u{2069}']),
            "{}: a plain call carried isolates: {plain:?}",
            language.id
        );
        assert_eq!(isolated.replace(['\u{2068}', '\u{2069}'], ""), plain);
        assert_eq!(
            ui.format_plain(Message::SettingsTitle),
            ui.format(Message::SettingsTitle),
            "{}: a message with nothing interpolated reads the same",
            language.id
        );
        // And the localizer itself is still a window's.
        assert_eq!(ui.rendering(), Rendering::Ui);
        assert!(ui
            .format_args(Message::LanguageSystem, &args)
            .contains('\u{2068}'));
    }
}

// ─── Negotiation ─────────────────────────────────────────────────────

#[test]
fn an_exact_tag_wins() {
    let chain = crate::negotiate(&LanguagePreference::parse("ru").expect("tag"));
    assert_eq!(
        chain.first().map(ToString::to_string).as_deref(),
        Some("ru")
    );
}

/// The reason a negotiation library is here at all: a desktop set to
/// Austrian German asks for `de-AT`, and this build ships `de`.
#[test]
fn a_region_falls_back_to_its_language() {
    let chain = crate::negotiate(&LanguagePreference::parse("de-AT").expect("tag"));
    assert_eq!(
        chain.first().map(ToString::to_string).as_deref(),
        Some("de")
    );
}

/// `pt-BR` must not quietly become `de` just because something has to
/// be first.
#[test]
fn an_unknown_language_lands_on_the_fallback() {
    let chain = crate::negotiate(&LanguagePreference::parse("pt-BR").expect("tag"));
    assert_eq!(
        chain.iter().map(ToString::to_string).collect::<Vec<_>>(),
        vec![FALLBACK_LANGUAGE.to_owned()]
    );
}

/// The chain is what makes a partial translation usable, so it must
/// always contain a catalogue that is complete.
///
/// *Contain*, not *end on*. `negotiate_languages` appends the default
/// only when the requested languages did not already ask for it, so a
/// desktop whose preference list reads `[en-US, ru]` gets that order
/// back and the chain ends on `ru`. That is the user's own ranking and
/// it is right; what would be wrong is a chain with no complete
/// catalogue anywhere in it, because then a missing translation has
/// nothing to fall through to.
#[test]
fn the_fallback_is_always_in_the_chain() {
    for preference in [
        LanguagePreference::System,
        LanguagePreference::parse("de").expect("tag"),
        LanguagePreference::parse("ru-RU").expect("tag"),
        LanguagePreference::parse("zxx").expect("tag"),
    ] {
        let chain: Vec<String> = crate::negotiate(&preference)
            .iter()
            .map(ToString::to_string)
            .collect();
        assert!(!chain.is_empty(), "{preference:?} negotiated to nothing");
        assert!(
            chain.iter().any(|language| language == FALLBACK_LANGUAGE),
            "{preference:?} produced {chain:?}, which has no complete catalogue in it"
        );

        let mut unique = chain.clone();
        unique.sort();
        unique.dedup();
        assert_eq!(
            unique.len(),
            chain.len(),
            "{preference:?} produced a chain with a repeated language: {chain:?}"
        );
    }
}

/// A desktop that never mentions the fallback still gets it, appended
/// behind everything it did ask for.
#[test]
fn a_chain_that_did_not_ask_for_english_still_ends_on_it() {
    let chain: Vec<String> = crate::negotiate(&LanguagePreference::parse("ru").expect("tag"))
        .iter()
        .map(ToString::to_string)
        .collect();
    assert_eq!(chain, vec!["ru".to_owned(), FALLBACK_LANGUAGE.to_owned()]);
}

/// A message the first catalogue does not define comes from the next
/// one, rather than showing the reader a key.
#[test]
fn a_lagging_translation_falls_through_rather_than_showing_a_key() {
    let partial = Localizer::from_sources(
        &[
            ("de", "panel-title = Schnelle Reinigung\n"),
            (
                "en-US",
                "panel-title = Quick scrub\nsettings-title = Settings\n",
            ),
        ],
        Rendering::PlainText,
    );

    assert_eq!(partial.format(Message::PanelTitle), "Schnelle Reinigung");
    assert_eq!(partial.format(Message::SettingsTitle), "Settings");
    assert!(!partial.defines(Message::SettingsTitle));
    assert_eq!(partial.language().to_string(), "de");
}

/// Nothing renders as a key unless no catalogue in the chain has it,
/// and then the key is the message — a blank label names nothing.
#[test]
fn a_message_no_catalogue_defines_renders_as_its_own_id() {
    let empty = Localizer::from_sources(&[("en-US", "")], Rendering::PlainText);
    assert_eq!(empty.format(Message::PanelTitle), "panel-title");
}

// ─── Plural rules ────────────────────────────────────────────────────

/// Why Fluent, and not a key-value table.
///
/// Russian selects on four CLDR categories and the boundaries are not
/// "== 1": 1 is *one*, 2–4 are *few*, 5 and up are *many*. No amount of
/// `format!` at the call site gets there without the translator writing
/// Rust, and the call site does not know which language it is in. The
/// catalogue does.
#[test]
fn plural_categories_come_from_the_language_not_the_call_site() {
    const RU: &str = "\
files = { $count ->
    [one] { $count } файл
    [few] { $count } файла
   *[other] { $count } файлов
}
";
    const EN: &str = "\
files = { $count ->
    [one] { $count } file
   *[other] { $count } files
}
";

    let russian = Localizer::from_sources(&[("ru", RU)], Rendering::PlainText);
    let english = Localizer::from_sources(&[("en-US", EN)], Rendering::PlainText);
    let files = Message::ALL
        .iter()
        .find(|message| message.id() == "files")
        .copied();
    assert!(
        files.is_none(),
        "`files` is a fixture; if it ships, test it through Message instead"
    );

    for (count, russian_form, english_form) in [
        (1, "1 файл", "1 file"),
        (3, "3 файла", "3 files"),
        (5, "5 файлов", "5 files"),
        (21, "21 файл", "21 files"),
    ] {
        assert_eq!(
            russian.format_raw("files", &args!("count" => count)),
            Some(russian_form.to_owned()),
            "russian, {count}"
        );
        assert_eq!(
            english.format_raw("files", &args!("count" => count)),
            Some(english_form.to_owned()),
            "english, {count}"
        );
    }
}

// ─── Catalogue hygiene ───────────────────────────────────────────────

/// What `build.rs` saw and what rust-embed baked in have to be the same
/// set. They are produced by two different globs over the same tree, so
/// a directory that one includes and the other does not is a language
/// that either cannot be chosen or cannot be loaded.
#[test]
fn the_embedded_catalogues_are_the_ones_that_were_built() {
    let embedded: Vec<String> = languages().iter().map(ToString::to_string).collect();
    let built: Vec<String> = BUILT_LANGUAGES.iter().map(|s| (*s).to_owned()).collect();
    assert_eq!(embedded, built);
}

/// The directory name *is* the language tag: it is what `bundle` looks
/// up and what negotiation matches on. `en_US` or `EN-us` would embed
/// fine and never be selected.
#[test]
fn catalogue_directories_are_canonical_language_tags() {
    for directory in BUILT_LANGUAGES {
        let parsed: LanguageIdentifier = directory
            .parse()
            .unwrap_or_else(|error| panic!("i18n/{directory}/ is not a language tag: {error}"));
        assert_eq!(
            parsed.to_string(),
            directory,
            "i18n/{directory}/ is not the canonical spelling of {parsed}"
        );
    }
}

/// Every language carries its own name, and no two carry the same one —
/// a selector with two entries reading "English" is a selector nobody
/// can use.
#[test]
fn every_language_names_itself_distinctly() {
    let mut autonyms: Vec<&str> = available_languages()
        .iter()
        .map(|language| {
            assert!(
                !language.autonym.is_empty(),
                "{} has no language-autonym",
                language.id
            );
            assert_ne!(
                language.autonym,
                language.id.to_string(),
                "{} fell back to its tag instead of naming itself",
                language.id
            );
            language.autonym.as_str()
        })
        .collect();
    autonyms.sort_unstable();
    let count = autonyms.len();
    autonyms.dedup();
    assert_eq!(count, autonyms.len(), "two languages share an autonym");
}

/// The status bar shows all three theme labels at once. Two that read
/// the same in some language is a selector with an unreachable option,
/// and it is a property of the catalogue rather than of the widget —
/// which is why it is gated here and not in the app, where testing it
/// would mean flipping a process-wide language under parallel tests.
#[test]
fn the_theme_labels_are_distinct_in_every_language() {
    const LABELS: [Message; 3] = [
        Message::ThemeSystem,
        Message::ThemeLight,
        Message::ThemeDark,
    ];
    for language in languages() {
        let localizer = only(&language);
        let mut rendered: Vec<String> = LABELS
            .iter()
            .map(|message| localizer.format(*message))
            .collect();
        rendered.sort();
        rendered.dedup();
        assert_eq!(rendered.len(), LABELS.len(), "{language}: {rendered:?}");
    }
}

/// The language selector lists `System (English)` above `English`. A
/// translation of `language-system` that dropped everything but the
/// placeholder would produce two rows reading the same word, and the
/// one the user needs — the one that follows the desktop — would be
/// indistinguishable from the one that pins a language forever.
#[test]
fn the_system_row_never_reads_as_a_plain_language_name() {
    for language in languages() {
        let localizer = only(&language);
        for other in available_languages() {
            let row = localizer.format_args(
                Message::LanguageSystem,
                &args!("language" => other.autonym.clone()),
            );
            assert_ne!(
                row, other.autonym,
                "{language}: the System row is indistinguishable from the {} row",
                other.id
            );
        }
    }
}

// ─── Preference ──────────────────────────────────────────────────────

/// `[ui] language` is a file format. This test is what makes renaming
/// one of these strings a deliberate act.
#[test]
fn config_values_round_trip() {
    for preference in [
        LanguagePreference::System,
        LanguagePreference::parse("de").expect("tag"),
        LanguagePreference::parse("en-US").expect("tag"),
    ] {
        assert_eq!(
            LanguagePreference::parse(&preference.as_config_value()),
            Some(preference.clone()),
            "{preference:?} did not survive a round trip"
        );
    }
}

/// A hand-edited config is expected to be sloppy, and `LANG` is not
/// BCP-47: `de_DE.UTF-8` is what a Unix shell actually exports.
#[test]
fn parsing_tolerates_the_spellings_a_desktop_produces() {
    assert_eq!(
        LanguagePreference::parse("de_DE.UTF-8"),
        LanguagePreference::parse("de-DE")
    );
    assert_eq!(
        LanguagePreference::parse("ru_RU@petr1708"),
        LanguagePreference::parse("ru-RU")
    );
    assert_eq!(
        LanguagePreference::parse("  AUTO\n"),
        Some(LanguagePreference::System)
    );
}

#[test]
fn unknown_values_are_not_guessed() {
    assert_eq!(LanguagePreference::parse(""), None);
    assert_eq!(LanguagePreference::parse("   "), None);
    assert_eq!(LanguagePreference::parse("not a language"), None);
}

/// A first launch follows the desktop, the same way the theme does.
#[test]
fn the_default_follows_the_system() {
    assert_eq!(LanguagePreference::default(), LanguagePreference::System);
    assert!(LanguagePreference::default().follows_system());
    assert!(!LanguagePreference::parse("de")
        .expect("tag")
        .follows_system());
}

/// Whatever the desktop is set to, `System` has to produce a chain that
/// can render a window. A machine with `LC_ALL=C` is not an error.
#[test]
fn system_always_resolves_to_something_renderable() {
    let localizer = Localizer::new(&LanguagePreference::System, Rendering::Ui);
    assert!(!localizer.chain().is_empty());
    assert!(!localizer.format(Message::WindowTitle).is_empty());
}

/// The documented precedence, in one place. Every level is exercised,
/// including the one that is skipped because it is nonsense.
#[test]
fn a_flag_beats_the_environment_beats_the_config_beats_the_desktop() {
    let german = LanguagePreference::parse("de").expect("tag");
    let russian = LanguagePreference::parse("ru").expect("tag");

    assert_eq!(
        LanguagePreference::resolve_from(Some("de"), Some("ru"), Some(russian.clone())),
        german,
        "the flag is the last word"
    );
    assert_eq!(
        LanguagePreference::resolve_from(None, Some("de"), Some(russian.clone())),
        german,
        "the environment beats the config file"
    );
    assert_eq!(
        LanguagePreference::resolve_from(None, None, Some(russian.clone())),
        russian,
        "the config file beats the desktop"
    );
    assert_eq!(
        LanguagePreference::resolve_from(None, None, None),
        LanguagePreference::System,
        "with nothing set, follow the desktop"
    );

    // A level that is not a language tag is skipped rather than
    // swallowing the ones below it.
    assert_eq!(
        LanguagePreference::resolve_from(Some("not a language"), Some("de"), None),
        german,
        "a nonsense flag must not hide the environment"
    );
}

/// Asking for `de-AT` and getting `de` is negotiation working. Asking
/// for `pt-BR` and getting English is not, and the CLI says so.
#[test]
fn a_request_is_honoured_by_its_own_language_whatever_the_region() {
    let austrian = LanguagePreference::parse("de-AT").expect("tag");
    let german: LanguageIdentifier = "de".parse().expect("tag");
    let english: LanguageIdentifier = FALLBACK_LANGUAGE.parse().expect("tag");

    assert!(austrian.is_honoured_by(&german));
    assert!(!austrian.is_honoured_by(&english));
    assert!(
        LanguagePreference::System.is_honoured_by(&english),
        "following the desktop is honoured by whatever it resolved to"
    );
}
