//! The Dock icon for a build that is not an `.app`.
//!
//! macOS reads an application's icon from its bundle: `CFBundleIconFile`
//! in `Info.plist`, resolved against `Contents/Resources`. A binary
//! started as `cargo run` or `./target/debug/wipemark` has no bundle, so
//! the Dock falls back to the generic executable icon no matter what
//! `[package.metadata.bundle]` says — that key is read by the *bundler*,
//! at packaging time, and is invisible at run time.
//!
//! So the artwork is embedded and handed to `NSApplication` directly.
//! This is a development affordance, not a replacement for E10: a
//! shipped `.app` still needs the `.icns` in its bundle for Finder, the
//! Launchpad, Spotlight and the "Open with" menu, none of which ever
//! launch this code.
//!
//! Setting it inside a bundle is harmless — the same artwork replaces
//! itself.

/// The 512×512 PNG generated by `icons/create-icons.sh`. Embedded rather
/// than read from disk so the binary keeps working when it is moved.
const ICON_PNG: &[u8] = include_bytes!("../assets/icon/icon.png");

/// Set the Dock icon. Silent no-op off the main thread or if AppKit
/// refuses the data — a missing icon is a cosmetic problem, and this is
/// not a reason to fail a launch.
///
/// Must be called after the `NSApplication` exists, i.e. from inside
/// `gpui_platform::application().run(…)`.
#[cfg(target_os = "macos")]
pub fn install() {
    use objc2::{AnyThread as _, MainThreadMarker};
    use objc2_app_kit::{NSApplication, NSImage};
    use objc2_foundation::NSData;

    let Some(mtm) = MainThreadMarker::new() else {
        tracing::debug!("dock icon skipped: not on the main thread");
        return;
    };

    let data = NSData::with_bytes(ICON_PNG);
    let Some(image) = NSImage::initWithData(NSImage::alloc(), &data) else {
        tracing::warn!("dock icon skipped: AppKit could not decode the embedded PNG");
        return;
    };

    // SAFETY: `mtm` proves we are on the main thread, which is the only
    // requirement AppKit places on this setter.
    unsafe { NSApplication::sharedApplication(mtm).setApplicationIconImage(Some(&image)) };
}

#[cfg(not(target_os = "macos"))]
pub fn install() {
    // Linux and Windows take the icon from the desktop entry and the
    // executable's resources respectively, both of which are packaging
    // concerns (E10). Nothing to do at run time.
}
