//! Typed SVG icons — the [`IconName`] enum and the [`Icon`] element.
//!
//! Epic **E6**. The enum is generated by `build.rs` from the SVG files
//! in `assets/icons/`; this module is the renderer and the sizing
//! vocabulary. See `docs/architecture/icons.md` for the FontAwesome
//! Free pull-and-promote workflow — the corpus is a public npm package,
//! and only the promoted SVGs are needed at build time.
//!
//! ```ignore
//! Icon::new(IconName::MagnifyingGlass)          // 16 px, theme foreground
//! Icon::new(IconName::TriangleExclamation)      // 12 px, explicit colour
//!     .small()
//!     .color(cx.theme().warning)
//! ```
//!
//! # `currentColor` is the contract
//!
//! [`Icon::color`] is `svg().text_color()` underneath, and GPUI only
//! substitutes that for paints written as `currentColor`. An icon
//! authored with `fill="#4a90d9"` renders blue in the dark theme, in
//! the light theme, and after `.color(red)` — silently, with no
//! warning. `every_icon_paints_with_current_color` below is what keeps
//! a hardcoded fill from reaching the window.

use gpui::prelude::*;
use gpui::{px, svg, App, Hsla, IntoElement, Window};
use gpui_component::ActiveTheme;

include!(concat!(env!("OUT_DIR"), "/icons_generated.rs"));

/// Our glyphs, wherever a `gpui-component` control asks for one of its
/// own.
///
/// The component library paints its icons through whatever
/// `AssetSource` the application registered — ours — so a
/// `Button::icon(gpui_component::IconName::Settings)` asks for
/// `icons/settings.svg`, a lucide name this repository does not ship,
/// and renders as blank space while logging `asset not found` once per
/// frame. `IconNamed` is the library's own escape hatch for exactly
/// that: `impl<T: IconNamed> From<T> for gpui_component::Icon` is
/// written over this trait, so implementing it here makes
/// `Button::new("appearance").icon(IconName::Sun)`,
/// `SidebarMenuItem::new(..).icon(IconName::Plug)` and every other
/// `impl Into<Icon>` parameter take a *promoted* FA Free file and
/// nothing else.
impl gpui_component::IconNamed for IconName {
    fn path(self) -> gpui::SharedString {
        // The inherent `IconName::path` wins name resolution here; the
        // two are the same string by construction, and
        // `every_icon_reaches_a_component_by_the_same_path` says so.
        IconName::path(self)
    }
}

/// Edge length of a rendered [`Icon`], in pixels.
///
/// The three presets are the sizes the shell actually uses: 12 px
/// inline in the status bar, 16 px for anything paired with body text,
/// 20 px where an affordance carries a pane on its own. Reach for
/// [`IconSize::Custom`] only when a design genuinely calls for a fourth
/// size — three that everything shares beats a pixel value per call
/// site.
#[derive(Copy, Clone, Debug, Default, PartialEq, Eq)]
#[allow(
    dead_code,
    reason = "the size vocabulary is complete by design; the E0 shell renders \
              only Small so far, E7 fills in the rest"
)]
pub enum IconSize {
    /// 12 px — dense inline: status bar, badges, table rows.
    Small,
    /// 16 px — the default, and the size that pairs with body text.
    #[default]
    Default,
    /// 20 px — emphasis: pane headers, primary affordances.
    Large,
    /// An arbitrary edge length in pixels.
    Custom(u32),
}

impl IconSize {
    fn pixels(self) -> f32 {
        match self {
            IconSize::Small => 12.0,
            IconSize::Default => 16.0,
            IconSize::Large => 20.0,
            IconSize::Custom(edge) => edge as f32,
        }
    }
}

/// A themed SVG glyph. Stateless builder; render it by handing it to
/// any GPUI parent as a child.
#[derive(IntoElement)]
pub struct Icon {
    name: IconName,
    size: IconSize,
    /// `None` means "follow the theme", resolved at render time rather
    /// than at construction — an icon built once and rendered across a
    /// theme switch has to change colour with everything else.
    color: Option<Hsla>,
}

#[allow(
    dead_code,
    reason = "builder surface matching IconSize; see the note on that enum"
)]
impl Icon {
    /// A new icon at the default size (16 px), painted in the active
    /// theme's foreground colour.
    pub fn new(name: IconName) -> Self {
        Self {
            name,
            size: IconSize::default(),
            color: None,
        }
    }

    /// Set the size explicitly. Prefer [`Icon::small`] / [`Icon::large`].
    pub fn size(mut self, size: IconSize) -> Self {
        self.size = size;
        self
    }

    /// The small (12 px) preset.
    pub fn small(mut self) -> Self {
        self.size = IconSize::Small;
        self
    }

    /// The large (20 px) preset.
    pub fn large(mut self) -> Self {
        self.size = IconSize::Large;
        self
    }

    /// Paint in `color` instead of the theme foreground.
    ///
    /// Only affects `currentColor` paints in the source SVG — see the
    /// module docs. Every bundled icon satisfies that, and a test
    /// enforces it.
    pub fn color(mut self, color: Hsla) -> Self {
        self.color = Some(color);
        self
    }
}

impl RenderOnce for Icon {
    fn render(self, _window: &mut Window, cx: &mut App) -> impl IntoElement {
        let color = self.color.unwrap_or_else(|| cx.theme().foreground);

        svg()
            .path(self.name.path())
            .text_color(color)
            .size(px(self.size.pixels()))
            // Icons never absorb the slack in a flex row — without
            // this a pane header icon stretches to fill the header.
            .flex_none()
    }
}

#[cfg(test)]
mod tests {
    use gpui::{div, point, size, AssetSource, TestAppContext};

    use super::*;
    use crate::assets::WipemarkAssets;

    #[test]
    fn the_icon_set_is_not_empty() {
        assert!(
            !ALL_ICONS.is_empty(),
            "assets/icons/ produced no variants — did the directory move?"
        );
    }

    #[test]
    fn every_id_is_kebab_case_and_round_trips_to_its_path() {
        for icon in ALL_ICONS.iter().copied() {
            let id = icon.id();
            assert!(!id.is_empty(), "{icon:?} has an empty id");
            assert!(
                id.chars()
                    .all(|c| c.is_ascii_lowercase() || c.is_ascii_digit() || c == '-'),
                "{icon:?} id {id:?} is not kebab-case"
            );
            assert_eq!(
                icon.path().as_ref(),
                format!("icons/{id}.svg"),
                "{icon:?}: path and id disagree"
            );
        }
    }

    #[test]
    fn every_icon_resolves_through_the_asset_source() {
        // The binding between the generated `path()` and the rust-embed
        // include pattern. Rename the directory, tighten the pattern, or
        // promote an icon into the wrong folder and this goes red here
        // rather than as blank space in the running window.
        for icon in ALL_ICONS.iter().copied() {
            let path = icon.path();
            let bytes = WipemarkAssets
                .load(&path)
                .unwrap_or_else(|e| panic!("{icon:?}: AssetSource::load({path}) failed: {e}"))
                .unwrap_or_else(|| panic!("{icon:?}: AssetSource returned None for {path}"));
            assert!(
                bytes.len() > 50,
                "{icon:?}: embedded asset is {} bytes — truncated?",
                bytes.len()
            );
        }
    }

    #[test]
    fn every_icon_reaches_a_component_by_the_same_path() {
        // The `IconNamed` bridge is what lets a gpui-component control
        // paint one of ours. An impl that returned anything but the
        // inherent path would send the component to a file the asset
        // source cannot resolve — blank space in the window, one log
        // line per frame, and nothing at the call site to look at.
        for icon in ALL_ICONS.iter().copied() {
            assert_eq!(
                gpui_component::IconNamed::path(icon),
                icon.path(),
                "{icon:?}: the component-facing path and the inherent one disagree"
            );
        }
    }

    #[test]
    fn every_icon_paints_with_current_color() {
        // The one property `Icon::color` depends on. A promoted SVG with
        // a hardcoded fill renders identically in both themes and
        // ignores every `.color()` call at the call site, with nothing
        // in the logs to say so.
        for icon in ALL_ICONS.iter().copied() {
            let src = icon.svg_source();
            assert!(src.contains("<svg"), "{icon:?} is not an SVG document");
            assert!(
                src.contains("currentColor"),
                "{icon:?} declares no `currentColor` paint, so `Icon::color` \
                 would silently no-op on it. Re-author the fill before promoting."
            );
        }
    }

    #[test]
    fn every_icon_is_a_free_glyph() {
        // The `NOTICE` says every file in `assets/icons/` is FontAwesome
        // *Free*, CC BY 4.0. FA writes the edition into each SVG's
        // attribution comment, and that comment is the only thing that
        // tells a Pro glyph from a Free one: the two share a filename,
        // a viewBox and — for anything Free carries — the path data. A
        // Pro file promoted by hand from an old corpus would look right
        // in the window, build cleanly and ship under the wrong
        // licence; this is the one place that gets noticed.
        for icon in ALL_ICONS.iter().copied() {
            let src = icon.svg_source();
            assert!(
                src.contains("Font Awesome Free"),
                "{icon:?} carries no `Font Awesome Free` attribution — the NOTICE \
                 says every glyph here is Free, and this one does not say so"
            );
            assert!(
                !src.contains("Font Awesome Pro"),
                "{icon:?} is a FontAwesome Pro file; this repository ships Free. \
                 Promote it again from the Free corpus (scripts/promote-icon.sh)."
            );
        }
    }

    #[test]
    fn size_presets_are_distinct_and_ordered() {
        assert_eq!(IconSize::default(), IconSize::Default);
        assert!(IconSize::Small.pixels() < IconSize::Default.pixels());
        assert!(IconSize::Default.pixels() < IconSize::Large.pixels());
        assert_eq!(IconSize::Custom(24).pixels(), 24.0);
    }

    #[gpui::test]
    fn an_icon_paints_at_the_size_it_was_given(cx: &mut TestAppContext) {
        // Guards the Styled-passthrough mistake: a builder that assigns
        // its own style over the element's (`*element.style() = ...`)
        // wipes the chained `.size(...)` in `render` and collapses every
        // icon to zero bounds. Every other test in this file still
        // passes in that state — only measuring painted bounds catches
        // it. Delete `.size(px(...))` from `Icon::render` and this must
        // go red.
        cx.update(gpui_component::init);
        let cx = cx.add_empty_window();

        cx.draw(
            point(px(0.0), px(0.0)),
            size(px(200.0), px(100.0)),
            |_, _| {
                div()
                    .flex()
                    .child(
                        div()
                            .debug_selector(|| "small".into())
                            .child(Icon::new(IconName::Check).small()),
                    )
                    .child(
                        div()
                            .debug_selector(|| "large".into())
                            .child(Icon::new(IconName::Check).large()),
                    )
                    .into_any_element()
            },
        );

        let small = cx
            .debug_bounds("small")
            .expect("the small icon never painted");
        let large = cx
            .debug_bounds("large")
            .expect("the large icon never painted");

        assert_eq!(small.size.width, px(12.0), "small preset is 12 px");
        assert_eq!(large.size.width, px(20.0), "large preset is 20 px");
        assert_eq!(large.size.height, px(20.0), "icons are square");
    }
}
