//! The menu-bar item: its icon, its menu, and the commands it sends.
//!
//! Epic **E6**. Modelled on heretic-lazy-shot's tray
//! (`packages/client/src-tauri/src/tray.rs`): a template icon the OS
//! recolours itself, a short menu of things worth doing without
//! bringing the window up, a submenu that mirrors live application
//! state, and a Quit. Tauri builds its tray on `tray-icon` and `muda`;
//! with no Tauri here we use those two crates directly, so the shape
//! carries over rather than being reinvented.
//!
//! # Why the menu talks to the app through a channel
//!
//! `muda` delivers a click to a `Fn(MenuEvent) + Send + Sync` callback
//! with nothing of ours in scope — there is no `&mut App` to be had
//! inside it, and no way to put one there. So the callback does the one
//! thing it can do without borrowing: it parses the id into a
//! [`TrayCommand`] and pushes it into a `flume` channel. `main` polls
//! that channel from `cx.spawn` and acts on the GPUI side of the wall.
//! It is the same arrangement every long operation in this codebase
//! uses, for the same reason (CLAUDE.md: nothing blocks the GPUI
//! thread).
//!
//! The parse lives on this side of the channel on purpose: a menu id is
//! a string, and a string that reaches the application as a string gets
//! matched on in three places by the second epic that touches it.
//!
//! # Platforms
//!
//! macOS only, today, and [`install`] returns `None` everywhere else —
//! `tray-icon` needs a GTK main loop on Linux and a win32 message pump
//! on Windows, neither of which a GPUI process runs. Those two are
//! packaging-shaped work for E10, alongside the `.desktop` entry and
//! the Windows resource script; the white icon variant they will need
//! is already generated by `icons/create-icons.sh`.

#[cfg(target_os = "macos")]
use wipemark_i18n::{t, Message};

use crate::theme::ThemePreference;

/// The 64 px black-on-transparent PNG that `icons/create-icons.sh`
/// installs. macOS scales whatever it is handed to 18 pt, so 64 px is
/// 3.5× the logical size and stays sharp on a Retina bar; it costs
/// about two kilobytes.
const TEMPLATE_PNG: &[u8] = include_bytes!("../assets/tray/tray-template.png");

/// Prefix of the appearance items' menu ids. The suffix is
/// [`ThemePreference::as_str`], which is also what `config.toml` holds —
/// one spelling of these three words in the whole product.
#[cfg_attr(
    not(target_os = "macos"),
    allow(
        dead_code,
        reason = "only the macOS tray builds a menu; the ids are still built and \
                  tested elsewhere so a spelling that does not round-trip fails that gate too"
    )
)]
const THEME_PREFIX: &str = "theme:";

/// What a click on a tray menu item asks the application to do.
///
/// Deliberately a value and not a callback: a callback would have to be
/// built inside the `muda` handler, which is exactly where no
/// application state can be reached.
#[cfg_attr(
    not(target_os = "macos"),
    allow(
        dead_code,
        reason = "only the macOS tray builds a menu; the ids are still built and \
                  tested elsewhere so a spelling that does not round-trip fails that gate too"
    )
)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum TrayCommand {
    /// Bring the window back. Closing the window hides the application
    /// rather than ending it (see `main`), so this is the way home.
    Show,
    /// The same three choices as the Settings dialog, kept in step with
    /// it in both directions.
    ///
    /// Kept in the menu even though Settings now holds the same three
    /// buttons: this is a submenu whose ticks a glance can read, and
    /// reaching it does not put a window on screen. lazy-shot's
    /// Displays submenu is the same bargain.
    Theme(ThemePreference),
    /// Summon the panel, or send it away if it is already on screen.
    ///
    /// The menu bar is what a summoned window is summoned *from*: it is
    /// reachable with the application hidden and with every window
    /// closed, which is the state the panel exists for. Where it
    /// appears is the Placement page's business — see
    /// `crate::placement`.
    Panel,
    /// Drop the local model from memory, whatever the keep mode — the
    /// Engine page's **Unload now**, reachable with every window closed.
    /// Enabled only while a model is loaded (see [`Tray::show_loaded`]).
    UnloadModel,
    /// Open the Settings dialog, bringing the window back first if it
    /// is hidden. Everything the tray cannot fit lives there.
    Settings,
    /// End the process — through GPUI's own shutdown, not AppKit's
    /// terminate. See the note on the Quit item in [`install`].
    Quit,
}

#[cfg_attr(
    not(target_os = "macos"),
    allow(
        dead_code,
        reason = "only the macOS tray builds a menu; the ids are still built and \
                  tested elsewhere so a spelling that does not round-trip fails that gate too"
    )
)]
impl TrayCommand {
    /// Every command the menu can produce, in menu order.
    ///
    /// Test-only, and hand-written on purpose. The menu itself is built
    /// item by item — Show, the appearance ticks and Quit are three
    /// different `muda` types, and no loop over this would produce it —
    /// so what the array is for is the id round-trip and the id
    /// uniqueness, neither of which reading the builder proves. A
    /// fourth command that is not added here fails
    /// `every_theme_the_app_offers_has_a_menu_command` rather than
    /// quietly going untested.
    #[cfg(test)]
    pub const ALL: [TrayCommand; 8] = [
        Self::Show,
        Self::Panel,
        Self::UnloadModel,
        Self::Theme(ThemePreference::System),
        Self::Theme(ThemePreference::Light),
        Self::Theme(ThemePreference::Dark),
        Self::Settings,
        Self::Quit,
    ];

    /// The id this command's menu item carries. Round-trips through
    /// [`TrayCommand::parse`].
    pub fn menu_id(self) -> String {
        match self {
            Self::Show => "show".to_owned(),
            Self::Panel => "panel".to_owned(),
            Self::UnloadModel => "unload-model".to_owned(),
            Self::Theme(choice) => format!("{THEME_PREFIX}{}", choice.as_str()),
            Self::Settings => "settings".to_owned(),
            Self::Quit => "quit".to_owned(),
        }
    }

    /// The command behind a menu id, or `None` for an id this build
    /// does not know — a disabled placeholder, or an item some later
    /// epic added and forgot to wire up. Never a guess: an unknown id
    /// that resolved to `Quit` by accident would be a very short bug
    /// report.
    pub fn parse(id: &str) -> Option<Self> {
        match id {
            "show" => Some(Self::Show),
            "panel" => Some(Self::Panel),
            "unload-model" => Some(Self::UnloadModel),
            "settings" => Some(Self::Settings),
            "quit" => Some(Self::Quit),
            other => other
                .strip_prefix(THEME_PREFIX)
                .and_then(ThemePreference::parse)
                .map(Self::Theme),
        }
    }
}

/// The decoded tray artwork, in the one form `tray-icon` accepts.
#[cfg_attr(
    not(target_os = "macos"),
    allow(
        dead_code,
        reason = "only the macOS tray installs an icon; the decode is still \
                  built and tested elsewhere so a broken asset fails that gate too"
    )
)]
struct TrayImage {
    rgba: Vec<u8>,
    width: u32,
    height: u32,
}

/// Decode [`TEMPLATE_PNG`].
///
/// `tray_icon::Icon` takes raw RGBA and nothing else, so the PNG has to
/// be unpacked before it can be installed. Kept out of the macOS block,
/// and tested on every platform, because the failure this guards
/// against is a bad *asset* — a re-export that came back as RGB, or a
/// blank canvas — and that is worth catching on whichever machine runs
/// the gate first.
#[cfg_attr(
    not(target_os = "macos"),
    allow(
        dead_code,
        reason = "only the macOS tray installs an icon; the decode is still \
                  built and tested elsewhere so a broken asset fails that gate too"
    )
)]
fn tray_image() -> anyhow::Result<TrayImage> {
    let mut reader = png::Decoder::new(TEMPLATE_PNG).read_info()?;
    let mut rgba = vec![0; reader.output_buffer_size()];
    let frame = reader.next_frame(&mut rgba)?;

    anyhow::ensure!(
        frame.color_type == png::ColorType::Rgba && frame.bit_depth == png::BitDepth::Eight,
        "the tray template must be 8-bit RGBA, not {:?} at {:?}",
        frame.color_type,
        frame.bit_depth
    );

    // `output_buffer_size` allows for the largest frame; the one we
    // read may be smaller, and `Icon::from_rgba` checks the length
    // against the dimensions.
    rgba.truncate(frame.buffer_size());

    Ok(TrayImage {
        rgba,
        width: frame.width,
        height: frame.height,
    })
}

/// The live menu-bar item.
///
/// Dropping it takes the icon out of the menu bar, so `main` parks it in
/// a GPUI global. Owning it from the window's view tree would be
/// backwards: the window is the thing the tray exists to bring back.
#[cfg(target_os = "macos")]
pub struct Tray {
    /// Never read. Held because the icon disappears when it drops.
    _icon: tray_icon::TrayIcon,
    /// The fixed items, held for their text. macOS builds this menu once
    /// and keeps it, so the only way a language change reaches the menu
    /// bar is by setting it again — see [`Tray::relabel`].
    items: Items,
    /// The Appearance submenu, so a choice made in the status bar can
    /// move the tick up here.
    appearance: Vec<(ThemePreference, tray_icon::menu::CheckMenuItem)>,
    commands: flume::Receiver<TrayCommand>,
}

/// The menu items whose text is prose rather than a name.
#[cfg(target_os = "macos")]
struct Items {
    show: tray_icon::menu::MenuItem,
    panel: tray_icon::menu::MenuItem,
    clipboard: tray_icon::menu::MenuItem,
    unload: tray_icon::menu::MenuItem,
    appearance: tray_icon::menu::Submenu,
    settings: tray_icon::menu::MenuItem,
    quit: tray_icon::menu::MenuItem,
}

/// There is no tray on this platform, and the type says so: `install`
/// returns `None`, nothing constructs one, and the call sites in `main`
/// still compile. See the platform note at the top of the module.
#[cfg(not(target_os = "macos"))]
pub enum Tray {}

impl gpui::Global for Tray {}

#[cfg(target_os = "macos")]
impl Tray {
    /// A receiver for the menu clicks. Cheap to clone; `main` takes one
    /// and polls it from `cx.spawn`.
    pub fn commands(&self) -> flume::Receiver<TrayCommand> {
        self.commands.clone()
    }

    /// Move the tick in the Appearance submenu.
    ///
    /// Called after *every* theme change, not just the ones that came
    /// from here: lazy-shot rebuilds its Displays submenu whenever the
    /// monitors change, and a submenu that shows stale state is worse
    /// than no submenu at all.
    pub fn show_theme(&self, choice: ThemePreference) {
        for (candidate, item) in &self.appearance {
            item.set_checked(*candidate == choice);
        }
    }

    /// Rewrite every label in the current language.
    ///
    /// The exact counterpart of [`Tray::show_theme`], and it exists for
    /// the same reason: this menu is built once at install and there is
    /// nothing that repaints it, so a menu bar left in the language the
    /// app started in is the tray version of a stale tick. Called from
    /// the GPUI foreground thread, which on macOS is the main thread —
    /// `muda` requires that.
    pub fn relabel(&self) {
        self.items.show.set_text(t(Message::TrayShow));
        self.items.panel.set_text(t(Message::TrayPanel));
        self.items
            .clipboard
            .set_text(t(Message::TrayCleanClipboard));
        self.items.unload.set_text(t(Message::TrayUnloadModel));
        self.items.appearance.set_text(t(Message::TrayAppearance));
        self.items.settings.set_text(t(Message::SettingsOpen));
        self.items.quit.set_text(t(Message::TrayQuit));
        for (choice, item) in &self.appearance {
            item.set_text(choice.label());
        }
    }

    /// Enable "Unload model" while a model is loaded, and only then.
    /// Called from the GPUI foreground thread — the main thread on macOS,
    /// which `muda` requires.
    pub fn show_loaded(&self, loaded: bool) {
        self.items.unload.set_enabled(loaded);
    }
}

#[cfg(not(target_os = "macos"))]
impl Tray {
    pub fn commands(&self) -> flume::Receiver<TrayCommand> {
        match *self {}
    }

    pub fn show_theme(&self, _choice: ThemePreference) {
        match *self {}
    }

    pub fn relabel(&self) {
        match *self {}
    }

    pub fn show_loaded(&self, _loaded: bool) {
        match *self {}
    }
}

/// Put the icon in the menu bar, with `current` ticked in the
/// Appearance submenu.
///
/// `None` means the menu bar has no Wipemark item and the application
/// carries on without one — the same judgement as `dock_icon`: an
/// affordance that failed to install is not a reason to fail a launch.
///
/// Must be called on the main thread, from inside
/// `gpui_platform::application().run(…)`, and only once: `muda` keeps
/// exactly one menu-event handler for the process (a `OnceCell`), so a
/// second call would build a menu whose clicks are delivered to the
/// first call's channel.
#[cfg(target_os = "macos")]
pub fn install(current: ThemePreference) -> Option<Tray> {
    use tray_icon::menu::{CheckMenuItem, Menu, MenuEvent, MenuItem, PredefinedMenuItem, Submenu};
    use tray_icon::{Icon, TrayIconBuilder};

    let image = match tray_image() {
        Ok(image) => image,
        Err(error) => {
            tracing::warn!(%error, "tray skipped: the embedded template icon did not decode");
            return None;
        }
    };
    let icon = match Icon::from_rgba(image.rgba, image.width, image.height) {
        Ok(icon) => icon,
        Err(error) => {
            tracing::warn!(%error, "tray skipped: the template icon was rejected");
            return None;
        }
    };

    let show = MenuItem::with_id(
        TrayCommand::Show.menu_id(),
        t(Message::TrayShow),
        true,
        None,
    );

    // The panel, which is the one window of this application that is
    // *summoned*: it has no titlebar and arrives where the Placement
    // page says. This is one of the two ways it is called up — the
    // other is the system-wide chord it ships with — and this one is
    // reachable with every window closed and the application hidden,
    // which is the state a summoned window exists for. Clicking it
    // again sends the panel away, the way the same item does in every
    // other menu bar; the label says the half somebody is looking for.
    let panel = MenuItem::with_id(
        TrayCommand::Panel.menu_id(),
        t(Message::TrayPanel),
        true,
        None,
    );

    // Disabled, and named after the epic that fills it in. The tray is
    // where lazy-shot puts its one-click captures, and the Wipemark
    // equivalent — scrub what is on the clipboard, without opening
    // anything — is Layer A work that does not exist yet. An item that
    // cannot be clicked is the honest version of that promise; an
    // enabled one that logs "not implemented" is not.
    let clipboard = MenuItem::with_id("clipboard", t(Message::TrayCleanClipboard), false, None);

    // The Engine page's Unload now, for a model kept loaded while every
    // window is closed. Disabled until the engine host says a model is in
    // memory — `main::install_tray` follows it from then on.
    let unload = MenuItem::with_id(
        TrayCommand::UnloadModel.menu_id(),
        t(Message::TrayUnloadModel),
        false,
        None,
    );

    let appearance: Vec<(ThemePreference, CheckMenuItem)> = ThemePreference::ALL
        .iter()
        .map(|choice| {
            let item = CheckMenuItem::with_id(
                TrayCommand::Theme(*choice).menu_id(),
                choice.label(),
                true,
                *choice == current,
                None,
            );
            (*choice, item)
        })
        .collect();

    let submenu = Submenu::with_id("appearance", t(Message::TrayAppearance), true);
    for (_, item) in &appearance {
        if let Err(error) = submenu.append(item) {
            tracing::warn!(%error, "tray skipped: the Appearance submenu could not be built");
            return None;
        }
    }

    // No accelerator, though the same command has one inside the
    // window: `muda` would draw ⌘, beside this item, and a menu bar is
    // exactly where someone would then try it with the window hidden —
    // where GPUI has no focused window to dispatch it to. A shortcut
    // that is advertised has to work from where it is advertised.
    let settings = MenuItem::with_id(
        TrayCommand::Settings.menu_id(),
        t(Message::SettingsOpen),
        true,
        None,
    );

    // Ours rather than `PredefinedMenuItem::quit`, which asks AppKit to
    // terminate the process directly. GPUI would never see the quit,
    // and neither would anything it runs on the way out.
    let quit = MenuItem::with_id(
        TrayCommand::Quit.menu_id(),
        t(Message::TrayQuit),
        true,
        None,
    );

    let menu = Menu::new();
    if let Err(error) = menu.append_items(&[
        &show,
        &panel,
        &clipboard,
        &unload,
        &PredefinedMenuItem::separator(),
        &submenu,
        &PredefinedMenuItem::separator(),
        // Settings above Quit and in the same group, which is where
        // every menu-bar application on this desktop puts it.
        &settings,
        &quit,
    ]) {
        tracing::warn!(%error, "tray skipped: the menu could not be built");
        return None;
    }

    let (sender, commands) = flume::unbounded();
    MenuEvent::set_event_handler(Some(move |event: MenuEvent| {
        let Some(command) = TrayCommand::parse(event.id.0.as_str()) else {
            // The disabled placeholder, or something a later epic added
            // to the menu and did not teach `parse` about.
            tracing::debug!(id = %event.id.0, "tray menu item with no command behind it");
            return;
        };
        if sender.send(command).is_err() {
            tracing::debug!("tray command dropped: nothing is listening any more");
        }
    }));

    let icon = match TrayIconBuilder::new()
        .with_id("wipemark")
        .with_menu(Box::new(menu))
        .with_tooltip("Wipemark")
        .with_icon(icon)
        // Black ink plus an alpha channel, and macOS inverts it for a
        // dark menu bar itself. The alternative is watching the system
        // appearance and swapping two PNGs, which is what Windows and
        // Linux will have to do, and what the white variant is for.
        .with_icon_as_template(true)
        .build()
    {
        Ok(icon) => icon,
        Err(error) => {
            tracing::warn!(%error, "tray skipped: the menu bar refused the item");
            return None;
        }
    };

    Some(Tray {
        _icon: icon,
        items: Items {
            show,
            panel,
            clipboard,
            unload,
            appearance: submenu,
            settings,
            quit,
        },
        appearance,
        commands,
    })
}

#[cfg(not(target_os = "macos"))]
pub fn install(_current: ThemePreference) -> Option<Tray> {
    tracing::debug!("no tray on this platform yet — E10");
    None
}

#[cfg(test)]
mod tests {
    use std::collections::BTreeSet;

    use super::*;

    #[test]
    fn every_command_round_trips_through_its_menu_id() {
        for command in TrayCommand::ALL {
            let id = command.menu_id();
            assert_eq!(
                TrayCommand::parse(&id),
                Some(command),
                "id {id:?} did not come back as {command:?}"
            );
        }
    }

    #[test]
    fn menu_ids_are_unique() {
        let ids: BTreeSet<String> = TrayCommand::ALL.iter().map(|c| c.menu_id()).collect();
        assert_eq!(
            ids.len(),
            TrayCommand::ALL.len(),
            "two menu items share an id, so one of them fires the other's command: {ids:?}"
        );
    }

    #[test]
    fn the_unload_command_round_trips_its_id() {
        let id = TrayCommand::UnloadModel.menu_id();
        assert_eq!(id, "unload-model");
        assert_eq!(TrayCommand::parse(&id), Some(TrayCommand::UnloadModel));
        assert_ne!(
            TrayCommand::parse("unload"),
            Some(TrayCommand::UnloadModel),
            "a near miss is not the command"
        );
    }

    #[test]
    fn an_unknown_menu_id_is_not_guessed() {
        for id in ["", "clipboard", "theme:", "theme:sepia", "shows", "Quit "] {
            assert_eq!(
                TrayCommand::parse(id),
                None,
                "{id:?} is not a command this build knows"
            );
        }
    }

    #[test]
    fn every_theme_the_app_offers_has_a_menu_command() {
        let offered: Vec<ThemePreference> = TrayCommand::ALL
            .iter()
            .filter_map(|command| match command {
                TrayCommand::Theme(choice) => Some(*choice),
                _ => None,
            })
            .collect();
        assert_eq!(
            offered,
            ThemePreference::ALL.to_vec(),
            "`install` builds the submenu straight from ThemePreference::ALL, so a new \
             preference reaches the menu bar whether or not anyone tested its id"
        );
    }

    #[test]
    fn the_template_decodes_to_what_the_menu_bar_takes() {
        let image = tray_image().expect("the embedded tray template decodes");
        assert_eq!(
            (image.width, image.height),
            (64, 64),
            "the installed template is not the 64 px square create-icons.sh writes"
        );
        assert_eq!(
            image.rgba.len(),
            (image.width * image.height * 4) as usize,
            "RGBA is four bytes a pixel; anything else is rejected by Icon::from_rgba"
        );
    }

    #[test]
    fn the_template_is_ink_on_transparency() {
        let image = tray_image().expect("the embedded tray template decodes");
        let alpha: Vec<u8> = image.rgba.chunks_exact(4).map(|pixel| pixel[3]).collect();

        // A rasterisation that silently produced an empty canvas, or a
        // solid square, both decode fine and both are invisible or
        // hideous in a menu bar. Nothing else here would notice.
        assert!(
            alpha.iter().any(|&a| a > 200),
            "the template has no opaque pixels — the export drew nothing"
        );
        assert!(
            alpha.contains(&0),
            "the template has no transparent pixels — this is a filled square, not a glyph"
        );
    }
}
