//! Compiles every `.wma` (an opacity map) and every `.wml` (a logo colour
//! map, E12-R9 — none ships yet) under `marks/` into the crate as a table
//! from file name to bytes, so a catalogue row names a file and the build
//! carries it — no runtime path, no data directory. Which files a
//! profile uses, and their hashes, are the catalogue's business: a file
//! listed here and named by no row is carried and never read, and a row
//! naming a file that is not here is `AssetProblem::Missing`.

use std::fmt::Write as _;
use std::path::{Path, PathBuf};

fn main() {
    let root = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").expect("cargo sets it"));
    let marks = root.join("marks");
    println!("cargo:rerun-if-changed={}", marks.display());
    let mut found = Vec::new();
    collect(&marks, &mut found);
    found.sort();
    let mut table = String::from(
        "/// Every `.wma` and `.wml` under `marks/`, by file name (generated by build.rs).\n\
         static ASSETS: &[(&str, &[u8])] = &[\n",
    );
    for path in &found {
        let name = path
            .file_name()
            .and_then(|n| n.to_str())
            .expect("an asset name is UTF-8");
        let _ = writeln!(
            table,
            "    ({name:?}, include_bytes!({:?})),",
            path.to_str().expect("an asset path is UTF-8")
        );
    }
    table.push_str("];\n");
    let out = PathBuf::from(std::env::var("OUT_DIR").expect("cargo sets it")).join("assets.rs");
    std::fs::write(out, table).expect("OUT_DIR is writable");
}

/// An asset this build carries: an opacity map or a logo colour map.
fn is_asset(path: &Path) -> bool {
    path.extension().is_some_and(|x| x == "wma" || x == "wml")
}

/// Every asset in `dir` and one level of folders below it.
fn collect(dir: &Path, found: &mut Vec<PathBuf>) {
    let Ok(entries) = std::fs::read_dir(dir) else {
        return;
    };
    for entry in entries.flatten() {
        let path = entry.path();
        if path.is_dir() {
            println!("cargo:rerun-if-changed={}", path.display());
            if let Ok(inner) = std::fs::read_dir(&path) {
                for e in inner.flatten() {
                    let p = e.path();
                    if is_asset(&p) {
                        found.push(p);
                    }
                }
            }
        } else if is_asset(&path) {
            found.push(path);
        }
    }
}
