//! Generates `OWN_CRATES` — the workspace's own crates, as `tracing`
//! targets — from the workspace manifest.
//!
//! Read from `Cargo.toml` rather than kept as a list in the source for
//! the same reason the i18n `Message` enum is generated from the
//! catalogue: a list that has to be maintained by hand is a list that
//! drifts. A crate added to the workspace and forgotten here would
//! silently log at `info` during development, and the person wondering
//! where their `debug!` went would have no reason to suspect this file.
//!
//! See `default_filter` in `src/lib.rs` for what the list is used for.

use std::path::PathBuf;

fn main() {
    let manifest = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"));
    // crates/wipemark-log -> crates -> the workspace root.
    let workspace = manifest
        .parent()
        .and_then(|crates| crates.parent())
        .expect("wipemark-log lives two levels below the workspace root")
        .join("Cargo.toml");

    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-changed={}", workspace.display());

    let document: toml::Table = std::fs::read_to_string(&workspace)
        .unwrap_or_else(|error| panic!("cannot read {}: {error}", workspace.display()))
        .parse()
        .unwrap_or_else(|error| panic!("cannot parse {}: {error}", workspace.display()));

    let members = document
        .get("workspace")
        .and_then(|workspace| workspace.get("members"))
        .and_then(toml::Value::as_array)
        .expect("[workspace] members");

    // `crates/wipemark-core` -> `wipemark_core`. A tracing target is a
    // module path, so the hyphen a crate name may carry is an
    // underscore by the time a filter sees it.
    let mut targets: Vec<String> = members
        .iter()
        .filter_map(toml::Value::as_str)
        .filter_map(|path| path.rsplit('/').next())
        .map(|name| name.replace('-', "_"))
        .collect();
    targets.sort();
    targets.dedup();
    assert!(!targets.is_empty(), "[workspace] members is empty");

    let list = targets
        .iter()
        .map(|target| format!("    {target:?},\n"))
        .collect::<String>();

    let out = PathBuf::from(std::env::var("OUT_DIR").expect("OUT_DIR")).join("own_crates.rs");
    std::fs::write(
        &out,
        format!("/// Generated by build.rs from the workspace manifest.\nconst OWN_CRATES: &[&str] = &[\n{list}];\n"),
    )
    .unwrap_or_else(|error| panic!("cannot write {}: {error}", out.display()));
}
