//! Code-generation of the typed [`IconName`] enum from the SVG files in
//! `assets/icons/`.
//!
//! Adding an icon is a one-step operation: drop a kebab-cased SVG into
//! `assets/icons/` and rebuild. There is no enum to extend by hand and
//! no match arm to keep in sync — which is the whole point. A hand-kept
//! enum drifts from the directory the first time someone promotes an
//! icon in a hurry, and the failure mode is a missing-asset warning at
//! paint time rather than a compile error.
//!
//! Emits `$OUT_DIR/icons_generated.rs`, included by `src/icon.rs`.
//! Render-side resolution goes through the `WipemarkAssets`
//! `AssetSource` (rust-embed backed) at runtime; `svg_source()` exists
//! for tests and introspection only.

use std::collections::HashMap;
use std::fmt::Write as _;
use std::path::{Path, PathBuf};
use std::{env, fs};

fn main() {
    llama_rpath();
    let manifest_dir = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    let icons_dir = manifest_dir.join("assets").join("icons");

    // The directory entry catches an added or removed file; the
    // per-file entries catch an edit in place, which does not touch the
    // directory's mtime.
    println!("cargo:rerun-if-changed={}", icons_dir.display());

    let mut entries: Vec<(String, PathBuf)> = Vec::new();
    if icons_dir.is_dir() {
        let read = fs::read_dir(&icons_dir)
            .unwrap_or_else(|e| panic!("read {}: {e}", icons_dir.display()));
        for res in read {
            let path = res.expect("read dir entry").path();
            if path.extension().and_then(|s| s.to_str()) != Some("svg") {
                continue;
            }
            println!("cargo:rerun-if-changed={}", path.display());
            let stem = path
                .file_stem()
                .and_then(|s| s.to_str())
                .unwrap_or_else(|| panic!("{}: non-UTF-8 filename", path.display()))
                .to_owned();
            entries.push((stem, path));
        }
    }

    if entries.is_empty() {
        println!("cargo:warning=assets/icons/ is empty; IconName will have zero variants.");
    }

    // Declaration order follows the filename, so the generated enum and
    // `ALL_ICONS` are stable across machines and readable in a diff.
    entries.sort_by(|a, b| a.0.cmp(&b.0));

    let mut variants: Vec<(String, String, PathBuf)> = Vec::with_capacity(entries.len());
    let mut seen: HashMap<String, PathBuf> = HashMap::with_capacity(entries.len());
    for (stem, path) in entries {
        validate_kebab_case(&stem, &path);
        let variant = pascal_case(&stem);
        // kebab → Pascal is injective for names that pass the validator
        // above, so this can only fire if the validator is loosened.
        // Hard-failing with both paths beats generating a duplicate
        // variant and letting rustc report it without either filename.
        if let Some(previous) = seen.insert(variant.clone(), path.clone()) {
            panic!(
                "icons codegen: duplicate variant `{variant}` from `{}` and `{}`",
                previous.display(),
                path.display()
            );
        }
        variants.push((stem, variant, path));
    }

    let out_path =
        PathBuf::from(env::var_os("OUT_DIR").expect("OUT_DIR")).join("icons_generated.rs");
    fs::write(&out_path, render(&variants))
        .unwrap_or_else(|e| panic!("write {}: {e}", out_path.display()));
}

/// The generated module, as text. Split out so the shape of the emitted
/// code is readable in one place.
fn render(variants: &[(String, String, PathBuf)]) -> String {
    let mut out = String::new();
    out.push_str(
        "// AUTO-GENERATED by apps/wipemark-app/build.rs — DO NOT EDIT.\n\
         // Source: apps/wipemark-app/assets/icons/\n\n\
         /// Typed identifier for every bundled icon, generated from\n\
         /// `apps/wipemark-app/assets/icons/*.svg` at build time. Dropping\n\
         /// an SVG into that directory produces a new variant on the next\n\
         /// `cargo build`.\n\
         #[derive(Copy, Clone, Debug, PartialEq, Eq, Hash)]\n\
         pub enum IconName {\n",
    );
    for (stem, variant, _) in variants {
        let _ = writeln!(out, "    /// `{stem}.svg`\n    {variant},");
    }
    out.push_str(
        "}\n\n\
         // The generator emits the whole surface, not the subset the app\n\
         // happens to render this week: `path` is used at every call site,\n\
         // `svg_source` and `id` by the tests and by future introspection.\n\
         // Trimming to what is live today would mean regenerating the API\n\
         // every time a pane grows an icon.\n\
         #[allow(dead_code, reason = \"generated API surface\")]\n\
         impl IconName {\n",
    );

    accessor(
        &mut out,
        variants,
        "    /// Raw SVG source text. For tests and introspection only —\n\
         \x20   /// rendering resolves [`IconName::path`] through\n\
         \x20   /// [`crate::assets::WipemarkAssets`] instead.\n\
         \x20   pub fn svg_source(self) -> &'static str {",
        |_, path| format!("include_str!({})", escape(&path.to_string_lossy())),
    );

    accessor(
        &mut out,
        variants,
        "    /// Logical asset path (`\"icons/<kebab>.svg\"`), resolved at\n\
         \x20   /// render time by the registered `AssetSource`.\n\
         \x20   pub fn path(self) -> ::gpui::SharedString {",
        |stem, _| format!("::gpui::SharedString::new_static(\"icons/{stem}.svg\")"),
    );

    accessor(
        &mut out,
        variants,
        "    /// Kebab-case identifier — the source filename without its\n\
         \x20   /// extension, and the name the icon has in FontAwesome.\n\
         \x20   pub fn id(self) -> &'static str {",
        |stem, _| escape(stem),
    );

    out.push_str("}\n\n");
    out.push_str(
        "/// Every icon variant, in declaration order. Drives the codegen\n\
         /// tests, and is how they enumerate what has to resolve.\n\
         #[allow(dead_code, reason = \"generated API surface; used by tests\")]\n\
         pub const ALL_ICONS: &[IconName] = &[\n",
    );
    for (_, variant, _) in variants {
        let _ = writeln!(out, "    IconName::{variant},");
    }
    out.push_str("];\n");
    out
}

/// One `match self`-over-every-variant accessor. The empty-set arm is
/// `match self {}` rather than a match with no arms, which is what
/// rustc accepts for an uninhabited enum — an empty `assets/icons/` has
/// to keep compiling, or a bad rebase leaves the crate unbuildable for
/// a reason that has nothing to do with the code.
fn accessor(
    out: &mut String,
    variants: &[(String, String, PathBuf)],
    signature: &str,
    body: impl Fn(&str, &Path) -> String,
) {
    out.push_str(signature);
    out.push('\n');
    if variants.is_empty() {
        out.push_str("        match self {}\n");
    } else {
        out.push_str("        match self {\n");
        for (stem, variant, path) in variants {
            let _ = writeln!(
                out,
                "            IconName::{variant} => {},",
                body(stem, path)
            );
        }
        out.push_str("        }\n");
    }
    out.push_str("    }\n\n");
}

/// `^[a-z][a-z0-9-]*$`, no doubled or trailing hyphen. The constraint
/// is not cosmetic: the stem becomes both a Rust identifier and an
/// asset path, and `pascal_case` is only injective over this alphabet.
fn validate_kebab_case(stem: &str, path: &Path) {
    let bad = |reason: &str| -> ! {
        panic!(
            "icons codegen: {} has an invalid name — {reason}. \
             Expected kebab-case ([a-z][a-z0-9-]*), matching the \
             FontAwesome source filename.",
            path.display()
        )
    };

    let mut chars = stem.chars();
    match chars.next() {
        Some(c) if c.is_ascii_lowercase() => {}
        _ => bad("must start with an ASCII lowercase letter"),
    }
    if chars.any(|c| !(c.is_ascii_lowercase() || c.is_ascii_digit() || c == '-')) {
        bad("only ASCII lowercase letters, digits and hyphens are allowed");
    }
    if stem.contains("--") || stem.ends_with('-') {
        bad("a doubled or trailing hyphen is not allowed");
    }
}

fn pascal_case(kebab: &str) -> String {
    let mut out = String::with_capacity(kebab.len());
    let mut upper_next = true;
    for c in kebab.chars() {
        if c == '-' {
            upper_next = true;
        } else if upper_next {
            out.extend(c.to_uppercase());
            upper_next = false;
        } else {
            out.push(c);
        }
    }
    out
}

/// A Rust string literal for `s`. Paths come from `read_dir` and are
/// almost always boring, but a backslash on Windows or a quote in a
/// checkout path would otherwise emit code that does not parse.
fn escape(s: &str) -> String {
    let mut out = String::with_capacity(s.len() + 2);
    out.push('"');
    for c in s.chars() {
        match c {
            '\\' => out.push_str("\\\\"),
            '"' => out.push_str("\\\""),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            c if (c as u32) < 0x20 => {
                let _ = write!(out, "\\u{{{:x}}}", c as u32);
            }
            c => out.push(c),
        }
    }
    out.push('"');
    out
}

/// Put llama.cpp's library directory on this binary's rpath, when it was
/// built in (`llama-native`).
///
/// `wipemark-llama-sys` links `libggml`, `libggml-base` and `libllama` as
/// shared libraries under its own `OUT_DIR`. `cargo run` and `cargo test`
/// find them because cargo puts that directory on the loader path; the
/// binary run by itself did not, and stopped at "libggml.so.0: cannot open
/// shared object file" before `main`. The sys crate hands the directory up
/// as `links` metadata, which reaches this script because the manifest
/// names the crate directly under `llama-native` — the prebuilt archive's
/// `lib/` by default, `OUT_DIR/lib` of a source build. Absent in every
/// other build, and then this prints nothing. Windows has no rpath: the sys
/// crate copies the DLLs beside the executables instead.
fn llama_rpath() {
    println!("cargo:rerun-if-env-changed=DEP_WIPEMARK_LLAMA_LIB_DIR");
    let windows = env::var("CARGO_CFG_TARGET_OS").as_deref() == Ok("windows");
    if let (Ok(dir), false) = (env::var("DEP_WIPEMARK_LLAMA_LIB_DIR"), windows) {
        println!("cargo:rustc-link-arg-bins=-Wl,-rpath,{dir}");
    }
}
