//! `wipemark-core` — Layer A, the deterministic half of the product.
//!
//! Everything here is verifiable: a code point either is a zero-width
//! joiner or it is not, and the report says exactly which ones were
//! removed and where. Nothing in this crate guesses, and nothing in it
//! calls a model. That separation is what lets the product's report
//! split findings into *verifiable* (this crate) and *best-effort*
//! ([`wipemark_engine`]-driven rewriting).
//!
//! # Zero dependencies, by rule
//!
//! This crate has no external dependencies and must keep none. The
//! Unicode tables it needs (`Default_Ignorable_Code_Point`,
//! `Emoji_Presentation`, `Emoji_Modifier_Base`, `confusables.txt`) are
//! generated by a `build.rs` from UCD text files committed to the repo
//! into sorted static ranges searched by binary search — the same
//! pattern `ml-tts-core` uses. A `unicode-*` crate would pin us to
//! someone else's UCD version and hide which version produced a
//! finding; the report has to name that version.
//!
//! # Skeleton status
//!
//! This is epic **E0**: the types are here, the logic is not. The
//! classifier, scrubber and guards land in epic E1 (see
//! `docs/architecture/skeleton.md`).

#![forbid(unsafe_code)]

pub mod class;
pub mod guard;
pub mod report;
pub mod vendor;

pub use class::{Action, Confidence, UnicodeClass, UnicodeFinding};
pub use guard::{Guard, GuardOutcome, RejectReason};
pub use report::{
    CleanReport, FinalReport, InspectReport, NormKind, RewriteSummary, RiskLabel, TextStats,
};
pub use vendor::Vendor;
