//! `wipemark-core` — Layer A, the deterministic half of the product.
//!
//! Everything here is verifiable: a code point either is a zero-width
//! joiner or it is not, and the report says exactly which ones were
//! removed and where. Nothing in this crate guesses, and nothing in it
//! calls a model. That separation is what lets the product's report
//! split findings into *verifiable* (this crate) and *best-effort*
//! ([`wipemark_engine`]-driven rewriting).
//!
//! # Zero dependencies, by rule
//!
//! This crate has no external dependencies and must keep none — not
//! even build dependencies. The Unicode tables it needs (twenty binary
//! properties and general categories, the scripts, the normalization
//! data, the confusables and the names of what can be a finding) are
//! generated by a `std`-only `build.rs` from the Unicode Character
//! Database files committed under `ucd/`, into sorted static tables
//! searched by binary search. The version, [`UNICODE_VERSION`], is read
//! from the files' own headers, and files of two versions fail the
//! build. A `unicode-*` crate would pin us to someone else's UCD version
//! and hide which version produced a finding; the report has to name
//! that version.
//!
//! # Skeleton status
//!
//! The Unicode tables and their lookups exist (E1-1). The classifier,
//! the scrubber and NFKC, the homoglyph detector and the guards land in
//! E1-2 … E1-5 (see `docs/plan/README.md` and
//! `docs/architecture/skeleton.md`).

#![forbid(unsafe_code)]

pub mod class;
pub mod guard;
mod name;
pub mod report;
mod script;
mod tables;
pub mod vendor;

pub use class::{Action, Confidence, UnicodeClass, UnicodeFinding};
pub use guard::{Guard, GuardOutcome, RejectReason};
pub use name::name_of;
pub use report::{
    CleanReport, FinalReport, InspectReport, NormKind, RewriteSummary, RiskLabel, TextStats,
};
pub use tables::UNICODE_VERSION;
pub use vendor::Vendor;
