//! The Unicode Character Database, as the lookups Layer A needs.
//!
//! The tables are generated by `build.rs` from the UCD files committed
//! under `crates/wipemark-core/ucd/` — Unicode [`UNICODE_VERSION`], read
//! from the files' own headers and never typed — into sorted statics in
//! `$OUT_DIR/tables.rs`, included below. Every lookup is a binary search:
//! a predicate over sorted inclusive `(first, last)` ranges, a value over
//! a table sorted by its key.
//!
//! Nothing outside this module may depend on a table's layout — only on
//! the functions below, which are the contract later E1 documents build
//! against (`docs/plan/README.md` §3.3). The one exception is `NAME`,
//! which `name.rs` reads.
//!
//! Each property is kept **as published**. Where Layer A wants something
//! narrower — `Zs` without U+0020, `Default_Ignorable_Code_Point` without
//! the Duployan and musical format controls (D19), an RTL paragraph that
//! a bidi control cannot vouch for (D20) — that subtraction is the
//! classifier's, written where the reason is, not hidden in a table.

// Module-wide, and kept so on purpose (E1-7): five lookups have no
// caller outside their unit tests — `is_join_control`, `is_format`,
// `is_emoji_presentation`, `is_emoji_modifier_base`,
// `is_emoji_component` — and neither have their five statics
// (`JOIN_CONTROL`, `FORMAT`, `EMOJI_PRESENTATION`, `EMOJI_MODIFIER_BASE`,
// `EMOJI_COMPONENT`), which live in the generated file `include!`d
// below, where an item attribute cannot reach without `build.rs`
// emitting it. `expect`, not `allow`: the day the last of them gains a
// caller the expectation goes unfulfilled and the build says to delete
// this line. Scoped to non-test builds so that a lookup with no unit
// test is still dead code to `cargo clippy --all-targets`.
#![cfg_attr(
    not(test),
    expect(
        dead_code,
        reason = "five UCD lookups and their generated statics have only test callers"
    )
)]

use std::cmp::Ordering;

use crate::script::Script;

include!(concat!(env!("OUT_DIR"), "/tables.rs"));

/// Whether `c` falls in one of the sorted, disjoint, inclusive ranges.
fn in_ranges(table: &[(u32, u32)], c: char) -> bool {
    let cp = u32::from(c);
    table
        .binary_search_by(|&(first, last)| {
            if last < cp {
                Ordering::Less
            } else if first > cp {
                Ordering::Greater
            } else {
                Ordering::Equal
            }
        })
        .is_ok()
}

/// `Default_Ignorable_Code_Point` (`DerivedCoreProperties.txt`), as
/// published: it includes reserved code points (U+2065, U+FFF0..U+FFF8,
/// U+E0000, …) and the format controls U+1BCA0..U+1BCA3 and
/// U+1D173..U+1D17A. D19 makes those two ranges never findings; that is
/// E1-2's subtraction in `class_of`, not this table's.
pub(crate) fn is_default_ignorable(c: char) -> bool {
    in_ranges(DEFAULT_IGNORABLE, c)
}

/// `Bidi_Control` (`PropList.txt`): twelve code points.
pub(crate) fn is_bidi_control(c: char) -> bool {
    in_ranges(BIDI_CONTROL, c)
}

/// `Variation_Selector` (`PropList.txt`): 260 code points, including the
/// Mongolian free variation selectors U+180B..U+180D and U+180F — and
/// not U+180E MONGOLIAN VOWEL SEPARATOR.
pub(crate) fn is_variation_selector(c: char) -> bool {
    in_ranges(VARIATION_SELECTOR, c)
}

/// `Join_Control` (`PropList.txt`): U+200C and U+200D.
pub(crate) fn is_join_control(c: char) -> bool {
    in_ranges(JOIN_CONTROL, c)
}

/// `Noncharacter_Code_Point` (`PropList.txt`): 66 code points.
pub(crate) fn is_noncharacter(c: char) -> bool {
    in_ranges(NONCHARACTER, c)
}

/// `General_Category=Co` (`UnicodeData.txt`): the three private-use
/// ranges, whole — each is a `First`/`Last` pair in the file.
pub(crate) fn is_private_use(c: char) -> bool {
    in_ranges(PRIVATE_USE, c)
}

/// `General_Category=Zs`. **Includes U+0020 SPACE**: the class
/// `ExoticSpace` is `Zs` minus U+0020, which is E1-2's subtraction.
pub(crate) fn is_space_separator(c: char) -> bool {
    in_ranges(SPACE_SEPARATOR, c)
}

/// `General_Category=Cf`.
pub(crate) fn is_format(c: char) -> bool {
    in_ranges(FORMAT, c)
}

/// `General_Category` ∈ {Lu, Ll, Lt, Lm, Lo}, including every letter
/// range `UnicodeData.txt` lists by its ends (CJK ideographs, Hangul
/// syllables, Tangut, Jurchen, Seal).
pub(crate) fn is_letter(c: char) -> bool {
    in_ranges(LETTER, c)
}

/// `General_Category` ∈ {Mn, Mc, Me}. Variation selectors are `Mn` and
/// therefore marks.
pub(crate) fn is_mark(c: char) -> bool {
    in_ranges(MARK, c)
}

/// `General_Category=Nd`.
pub(crate) fn is_decimal_digit(c: char) -> bool {
    in_ranges(DECIMAL_DIGIT, c)
}

/// `General_Category=Lu`. A titlecase letter (`Lt`) is neither upper nor
/// lower.
pub(crate) fn is_uppercase_letter(c: char) -> bool {
    in_ranges(UPPERCASE_LETTER, c)
}

/// `General_Category=Ll`.
pub(crate) fn is_lowercase_letter(c: char) -> bool {
    in_ranges(LOWERCASE_LETTER, c)
}

/// `Bidi_Class` ∈ {R, AL}, from `UnicodeData.txt`, as published: **true
/// for U+200F RIGHT-TO-LEFT MARK (`R`) and U+061C ARABIC LETTER MARK
/// (`AL`)**. That a paragraph is right-to-left only through an R/AL
/// *letter or mark* (D20) is E1-2's filter on top. False for every
/// unassigned code point: the block defaults of `DerivedBidiClass.txt`
/// are not committed.
pub(crate) fn is_rtl(c: char) -> bool {
    in_ranges(RTL, c)
}

/// `Emoji` (`emoji/emoji-data.txt`). True for the keycap and text-default
/// bases — `#`, `*`, `0`–`9`, U+00A9, U+00AE, U+2122, U+2139; false for
/// U+200D, U+FE0F and the tags.
pub(crate) fn is_emoji(c: char) -> bool {
    in_ranges(EMOJI, c)
}

/// `Emoji_Presentation` (`emoji/emoji-data.txt`).
pub(crate) fn is_emoji_presentation(c: char) -> bool {
    in_ranges(EMOJI_PRESENTATION, c)
}

/// `Emoji_Modifier` (`emoji/emoji-data.txt`): the skin tones
/// U+1F3FB..U+1F3FF.
pub(crate) fn is_emoji_modifier(c: char) -> bool {
    in_ranges(EMOJI_MODIFIER, c)
}

/// `Emoji_Modifier_Base` (`emoji/emoji-data.txt`).
pub(crate) fn is_emoji_modifier_base(c: char) -> bool {
    in_ranges(EMOJI_MODIFIER_BASE, c)
}

/// `Emoji_Component` (`emoji/emoji-data.txt`): includes U+200D, U+20E3,
/// U+FE0F, the regional indicators, the skin tones, the hair components
/// and the tags U+E0020..U+E007F.
pub(crate) fn is_emoji_component(c: char) -> bool {
    in_ranges(EMOJI_COMPONENT, c)
}

/// `Script=Han` (`Scripts.txt`). Agrees with `script_of(c) ==
/// Script::Han` for every code point.
pub(crate) fn is_han(c: char) -> bool {
    in_ranges(HAN, c)
}

/// The `Script` of `c` (`Scripts.txt`), folded into [`Script`]: `Other`
/// for every script the product does not name, for `Unknown`, and for
/// unassigned, private-use and noncharacter code points. Combining marks
/// of `Script=Inherited`, and U+200C/U+200D, are `Inherited` — resolving
/// them to the script of their base is the caller's.
pub(crate) fn script_of(c: char) -> Script {
    let cp = u32::from(c);
    let index = SCRIPT.partition_point(|&(_, last, _)| last < cp);
    match SCRIPT.get(index) {
        Some(&(first, _, script)) if first <= cp => script,
        _ => Script::Other,
    }
}

/// Whether `(base, selector)` is a standardized variation sequence of
/// `StandardizedVariants.txt`. Emoji presentation sequences (`…
/// U+FE0F`) and ideographic variation sequences (the IVD) are **not** in
/// that file, and this answers false for them.
pub(crate) fn is_standardized_variant(base: char, selector: char) -> bool {
    STANDARDIZED_VARIANTS
        .binary_search(&(u32::from(base), u32::from(selector)))
        .is_ok()
}

/// The full NFKD mapping of `c` — every canonical and compatibility
/// decomposition applied recursively at build time — or `None` when `c`
/// has none. **Not** in canonical order: reordering by `ccc` is a runtime
/// step over the whole string. `None` for Hangul syllables, whose
/// decomposition is arithmetic (E1-3).
pub(crate) fn decomposition(c: char) -> Option<&'static [char]> {
    let index = DECOMPOSITION
        .binary_search_by_key(&u32::from(c), |&(cp, _, _)| cp)
        .ok()?;
    let (_, offset, length) = DECOMPOSITION[index];
    let offset = usize::from(offset);
    Some(&DECOMPOSITION_POOL[offset..offset + usize::from(length)])
}

/// `Canonical_Combining_Class` (`UnicodeData.txt`); 0 when not listed.
pub(crate) fn ccc(c: char) -> u8 {
    let cp = u32::from(c);
    let index = CCC.partition_point(|&(_, last, _)| last < cp);
    match CCC.get(index) {
        Some(&(first, _, class)) if first <= cp => class,
        _ => 0,
    }
}

/// The primary composite of `first` followed by `second`: a canonical
/// two-code-point mapping not in `Full_Composition_Exclusion`. `None` for
/// excluded composites, for non-starter decompositions (which are
/// excluded), and for Hangul (arithmetic, E1-3).
pub(crate) fn compose(first: char, second: char) -> Option<char> {
    COMPOSITION
        .binary_search_by_key(&(u32::from(first), u32::from(second)), |&(pair, _)| pair)
        .ok()
        .map(|index| COMPOSITION[index].1)
}

/// `Some(skeleton)` when `c` is a kept source of `confusables.txt`: a
/// letter (`gc=L*`) of `Script` Latin, Cyrillic or Greek whose skeleton
/// is one code point (D22). `None` for everything else — **including a
/// prototype** (U+0061 is the skeleton of others and has none of its
/// own) and every halfwidth Katakana or Hangul letter. A caller's
/// skeleton is `confusable_target(c).unwrap_or(c)`.
pub(crate) fn confusable_target(c: char) -> Option<char> {
    CONFUSABLE
        .binary_search_by_key(&u32::from(c), |&(source, _)| source)
        .ok()
        .map(|index| CONFUSABLE[index].1)
}

/// Every homoglyph-capable letter whose skeleton is `target` and whose
/// script is `script`, ascending — including `target` itself when it is
/// a letter of that script. May hold several letters, including letters
/// **with a decomposition** (U+FF41 is in the Latin list for `a`):
/// choosing among them (D21, D42) is E1-4's. An empty slice when there
/// are none, and for any script other than Latin, Cyrillic or Greek.
pub(crate) fn confusables_with(target: char, script: Script) -> &'static [char] {
    let skeleton = u32::from(target);
    let start = CONFUSABLE_REVERSE.partition_point(|&(key, _, _)| key < skeleton);
    CONFUSABLE_REVERSE[start..]
        .iter()
        .take_while(|&&(key, _, _)| key == skeleton)
        .find(|&&(_, of, _)| of == script)
        .map_or(&[], |&(_, _, members)| members)
}

#[cfg(test)]
mod tests {
    //! Every lookup against the UCD file it comes from, read again here
    //! independently: a few lines of `split(';')` and `from_str_radix`
    //! that share no code with `build.rs`. "Exhaustive" means every
    //! `char`.

    use super::*;
    use crate::script::tests::ALL as ALL_SCRIPTS;

    const UNICODE_DATA: &str = include_str!("../ucd/UnicodeData.txt");
    const PROP_LIST: &str = include_str!("../ucd/PropList.txt");
    const DERIVED_CORE: &str = include_str!("../ucd/DerivedCoreProperties.txt");
    const DERIVED_NORMALIZATION: &str = include_str!("../ucd/DerivedNormalizationProps.txt");
    const SCRIPTS: &str = include_str!("../ucd/Scripts.txt");
    const EMOJI_DATA: &str = include_str!("../ucd/emoji/emoji-data.txt");

    const LIMIT: usize = 0x11_0000;

    fn chars() -> impl Iterator<Item = char> {
        (0..=0x10_FFFF).filter_map(char::from_u32)
    }

    fn ch(cp: u32) -> char {
        char::from_u32(cp).expect("a scalar value")
    }

    fn hex(text: &str) -> u32 {
        u32::from_str_radix(text.trim(), 16).expect("hex")
    }

    /// The data fields of a property-file line, comment cut, trimmed.
    fn fields(line: &str) -> Option<Vec<&str>> {
        let data = line.split('#').next().unwrap_or("").trim();
        (!data.is_empty()).then(|| data.split(';').map(str::trim).collect())
    }

    fn span(field: &str) -> std::ops::RangeInclusive<u32> {
        match field.split_once("..") {
            Some((first, last)) => hex(first)..=hex(last),
            None => hex(field)..=hex(field),
        }
    }

    /// Every code point of the 2-field lines whose value is `value`.
    fn listed(text: &str, value: &str) -> Vec<bool> {
        let mut set = vec![false; LIMIT];
        for fields in text.lines().filter_map(fields) {
            if fields.len() == 2 && fields[1] == value {
                for cp in span(fields[0]) {
                    set[cp as usize] = true;
                }
            }
        }
        assert!(set.contains(&true), "{value} is in its file");
        set
    }

    #[derive(Clone, Copy)]
    struct Row {
        gc: &'static str,
        ccc: u8,
        bidi: &'static str,
    }

    /// `UnicodeData.txt`, one row per code point, `First`/`Last` pairs
    /// expanded.
    fn unicode_data() -> Vec<Option<Row>> {
        let mut rows = vec![None; LIMIT];
        let mut first = None;
        for line in UNICODE_DATA.lines() {
            let fields: Vec<&str> = line.split(';').collect();
            let cp = hex(fields[0]);
            let row = Row {
                gc: fields[2],
                ccc: fields[3].parse().expect("ccc"),
                bidi: fields[4],
            };
            if fields[1].ends_with(", First>") {
                first = Some(cp);
                continue;
            }
            let start = if fields[1].ends_with(", Last>") {
                first.take().expect("a First before its Last")
            } else {
                cp
            };
            for code in start..=cp {
                rows[code as usize] = Some(row);
            }
        }
        rows
    }

    #[test]
    fn a_range_holds_both_of_its_ends() {
        for (cp, expected) in [
            (0x202A, true),
            (0x202E, true),
            (0x2029, false),
            (0x202F, false),
        ] {
            assert_eq!(is_bidi_control(ch(cp)), expected, "U+{cp:04X}");
        }
        for (cp, expected) in [
            (0xE0100, true),
            (0xE01EF, true),
            (0xE01F0, false),
            (0xE00FF, false),
        ] {
            assert_eq!(is_variation_selector(ch(cp)), expected, "U+{cp:04X}");
        }
        for (cp, expected) in [
            (0xE000, true),
            (0xF8FF, true),
            (0xF0000, true),
            (0xFFFFD, true),
            (0x10_0000, true),
            (0x10_FFFD, true),
            (0xF900, false),
            (0xFFFFE, false),
            (0x10_FFFE, false),
        ] {
            assert_eq!(is_private_use(ch(cp)), expected, "U+{cp:04X}");
        }
    }

    type Lookup = fn(char) -> bool;

    #[test]
    fn every_binary_property_matches_its_file() {
        let properties: [(&str, Vec<bool>, Lookup); 11] = [
            (
                "Bidi_Control",
                listed(PROP_LIST, "Bidi_Control"),
                is_bidi_control,
            ),
            (
                "Variation_Selector",
                listed(PROP_LIST, "Variation_Selector"),
                is_variation_selector,
            ),
            (
                "Join_Control",
                listed(PROP_LIST, "Join_Control"),
                is_join_control,
            ),
            (
                "Noncharacter_Code_Point",
                listed(PROP_LIST, "Noncharacter_Code_Point"),
                is_noncharacter,
            ),
            (
                "Default_Ignorable_Code_Point",
                listed(DERIVED_CORE, "Default_Ignorable_Code_Point"),
                is_default_ignorable,
            ),
            ("Emoji", listed(EMOJI_DATA, "Emoji"), is_emoji),
            (
                "Emoji_Presentation",
                listed(EMOJI_DATA, "Emoji_Presentation"),
                is_emoji_presentation,
            ),
            (
                "Emoji_Modifier",
                listed(EMOJI_DATA, "Emoji_Modifier"),
                is_emoji_modifier,
            ),
            (
                "Emoji_Modifier_Base",
                listed(EMOJI_DATA, "Emoji_Modifier_Base"),
                is_emoji_modifier_base,
            ),
            (
                "Emoji_Component",
                listed(EMOJI_DATA, "Emoji_Component"),
                is_emoji_component,
            ),
            ("Han", listed(SCRIPTS, "Han"), is_han),
        ];
        for (name, set, lookup) in &properties {
            for c in chars() {
                assert_eq!(
                    lookup(c),
                    set[c as usize],
                    "{name} at U+{:04X}",
                    u32::from(c)
                );
            }
        }
    }

    #[test]
    fn every_general_category_predicate_matches_unicode_data() {
        let rows = unicode_data();
        for c in chars() {
            let row = rows[c as usize];
            let gc = row.map_or("Cn", |row| row.gc);
            let at = format!("U+{:04X} ({gc})", u32::from(c));
            assert_eq!(is_private_use(c), gc == "Co", "{at}");
            assert_eq!(is_space_separator(c), gc == "Zs", "{at}");
            assert_eq!(is_format(c), gc == "Cf", "{at}");
            assert_eq!(
                is_letter(c),
                matches!(gc, "Lu" | "Ll" | "Lt" | "Lm" | "Lo"),
                "{at}"
            );
            assert_eq!(is_mark(c), matches!(gc, "Mn" | "Mc" | "Me"), "{at}");
            assert_eq!(is_decimal_digit(c), gc == "Nd", "{at}");
            assert_eq!(is_uppercase_letter(c), gc == "Lu", "{at}");
            assert_eq!(is_lowercase_letter(c), gc == "Ll", "{at}");
            assert_eq!(
                is_rtl(c),
                row.is_some_and(|row| matches!(row.bidi, "R" | "AL")),
                "{at}"
            );
            assert_eq!(ccc(c), row.map_or(0, |row| row.ccc), "{at}");
        }
    }

    /// A §4.1 spells these sets out by hand, and E1-2's classes are
    /// written against those spellings. If a version bump turns this red,
    /// Unicode changed a set E1-2's table is written against — read A
    /// §4.1 before touching either.
    #[test]
    fn the_sets_layer_a_names_by_hand_are_the_sets_unicode_gives() {
        for c in chars() {
            let cp = u32::from(c);
            let at = format!("U+{cp:04X}");
            assert_eq!(
                is_bidi_control(c),
                matches!(cp, 0x061C | 0x200E | 0x200F | 0x202A..=0x202E | 0x2066..=0x2069),
                "{at}"
            );
            assert_eq!(is_join_control(c), matches!(cp, 0x200C | 0x200D), "{at}");
            assert_eq!(
                is_variation_selector(c),
                matches!(cp, 0x180B..=0x180D | 0x180F | 0xFE00..=0xFE0F | 0xE0100..=0xE01EF),
                "{at}"
            );
            assert_eq!(
                is_noncharacter(c),
                (0xFDD0..=0xFDEF).contains(&cp) || cp & 0xFFFE == 0xFFFE,
                "{at}"
            );
            assert_eq!(
                is_private_use(c),
                matches!(cp, 0xE000..=0xF8FF | 0xF0000..=0xFFFFD | 0x10_0000..=0x10_FFFD),
                "{at}"
            );
            assert_eq!(
                is_space_separator(c) && c != ' ',
                matches!(
                    cp,
                    0x00A0 | 0x1680 | 0x2000..=0x200A | 0x202F | 0x205F | 0x3000
                ),
                "{at}"
            );
        }
    }

    #[test]
    fn letters_and_private_use_cover_the_ranges_unicode_data_lists_by_their_ends() {
        for cp in [
            0x3400, 0x4DBF, 0x4E01, 0x9FFF, 0xAC01, 0xD7A3, 0x17001, 0x18E00, 0x323B0, 0x3D001,
            0x3FC3F,
        ] {
            assert!(is_letter(ch(cp)), "U+{cp:04X} is a letter");
        }
        for cp in [0x4E01, 0x20001] {
            assert!(is_han(ch(cp)), "U+{cp:04X} is Han");
        }
        for cp in [0xE001, 0xF0001, 0x10_FFFD] {
            assert!(is_private_use(ch(cp)), "U+{cp:04X} is private use");
        }
        for cp in [0xE001, 0x0378] {
            assert!(!is_letter(ch(cp)), "U+{cp:04X} is not a letter");
        }
    }

    #[test]
    fn rtl_means_bidi_class_r_or_al() {
        for cp in [0x05D0, 0x0627, 0x0640, 0x07C0, 0xFB1D, 0x200F, 0x061C] {
            assert!(is_rtl(ch(cp)), "U+{cp:04X} is R or AL");
        }
        for cp in [0x200E, 0x0061, 0x0661, 0x202E, 0x2067, 0x0378] {
            assert!(!is_rtl(ch(cp)), "U+{cp:04X} is neither R nor AL");
        }
    }

    #[test]
    fn emoji_properties_are_read_separately() {
        let check = |name: &str, lookup: fn(char) -> bool, yes: &[u32], no: &[u32]| {
            for &cp in yes {
                assert!(lookup(ch(cp)), "{name} at U+{cp:04X}");
            }
            for &cp in no {
                assert!(!lookup(ch(cp)), "not {name} at U+{cp:04X}");
            }
        };
        check(
            "Emoji",
            is_emoji,
            &[0x0023, 0x0030, 0x00A9, 0x2139, 0x2764, 0x1F600],
            &[0x0041, 0x200D, 0xFE0F, 0xE0020],
        );
        check(
            "Emoji_Presentation",
            is_emoji_presentation,
            &[0x1F600, 0x1F525],
            &[0x2139, 0x2764, 0x0023],
        );
        check(
            "Emoji_Modifier",
            is_emoji_modifier,
            &[0x1F3FB, 0x1F3FF],
            &[0x1F3FA, 0x1F44D],
        );
        check(
            "Emoji_Modifier_Base",
            is_emoji_modifier_base,
            &[0x1F44D, 0x1F469],
            &[0x1F600, 0x2764],
        );
        check(
            "Emoji_Component",
            is_emoji_component,
            &[
                0x0023, 0x0030, 0x200D, 0x20E3, 0xFE0F, 0x1F1E6, 0x1F3FB, 0xE0020, 0xE007F,
            ],
            &[0x2764, 0xFE0E, 0xE0001],
        );
    }

    #[test]
    fn script_of_folds_scripts_txt_into_the_enum() {
        let expected = [
            (0x0041, Script::Latin),
            (0x0430, Script::Cyrillic),
            (0x03B1, Script::Greek),
            (0x0627, Script::Arabic),
            (0x05D0, Script::Hebrew),
            (0x4E00, Script::Han),
            (0x3005, Script::Han),
            (0x3042, Script::Hiragana),
            (0x30A2, Script::Katakana),
            (0xAC00, Script::Hangul),
            (0x3105, Script::Bopomofo),
            (0x0710, Script::Syriac),
            (0x07CA, Script::Nko),
            (0x0840, Script::Mandaic),
            (0x1E900, Script::Adlam),
            (0x10D00, Script::HanifiRohingya),
            (0x0915, Script::Devanagari),
            (0x0B15, Script::Oriya),
            (0x0F40, Script::Tibetan),
            (0x1780, Script::Khmer),
            (0x1820, Script::Mongolian),
            (0x1A20, Script::TaiTham),
            (0xABC0, Script::MeeteiMayek),
            (0x11400, Script::Newa),
            (0x10F30, Script::Sogdian),
            (0x10AC0, Script::Manichaean),
            (0x10F70, Script::OldUyghur),
            (0x0020, Script::Common),
            (0x0640, Script::Common),
            (0x30FC, Script::Common),
            (0x0301, Script::Inherited),
            (0x3099, Script::Inherited),
            (0x200D, Script::Inherited),
            (0x0E01, Script::Other),
            (0x0531, Script::Other),
            (0x10FB0, Script::Other),
            (0x0378, Script::Other),
            (0xE000, Script::Other),
        ];
        for (cp, script) in expected {
            assert_eq!(script_of(ch(cp)), script, "U+{cp:04X}");
        }
    }

    #[test]
    fn script_of_matches_scripts_txt_for_every_code_point() {
        let mut value: Vec<Option<&str>> = vec![None; LIMIT];
        for fields in SCRIPTS.lines().filter_map(fields) {
            for cp in span(fields[0]) {
                value[cp as usize] = Some(fields[1]);
            }
        }
        for c in chars() {
            let expected = value[c as usize]
                .and_then(|name| {
                    ALL_SCRIPTS
                        .iter()
                        .copied()
                        .find(|&script| script != Script::Other && script.as_str() == name)
                })
                .unwrap_or(Script::Other);
            assert_eq!(script_of(c), expected, "U+{:04X}", u32::from(c));
        }
    }

    #[test]
    fn is_han_agrees_with_script_of() {
        for c in chars() {
            assert_eq!(
                is_han(c),
                script_of(c) == Script::Han,
                "U+{:04X}",
                u32::from(c)
            );
        }
    }

    #[test]
    fn standardized_variants_are_pairs_of_base_then_selector() {
        for (base, selector) in [(0x0030, 0xFE00), (0x1820, 0x180B), (0x349E, 0xFE00)] {
            assert!(
                is_standardized_variant(ch(base), ch(selector)),
                "U+{base:04X} U+{selector:04X}"
            );
        }
        for (base, selector) in [
            (0xFE00, 0x0030),
            (0x0041, 0xFE00),
            (0x2139, 0xFE0F),
            (0x2764, 0xFE0F),
            (0x4E00, 0xE0100),
            (0x1820, 0x180F),
        ] {
            assert!(
                !is_standardized_variant(ch(base), ch(selector)),
                "U+{base:04X} U+{selector:04X}"
            );
        }
    }

    fn chars_of(cps: &[u32]) -> Vec<char> {
        cps.iter().map(|&cp| ch(cp)).collect()
    }

    #[test]
    fn decompositions_are_expanded_all_the_way_down() {
        let expected: [(u32, &[u32]); 11] = [
            (0x00C5, &[0x0041, 0x030A]),
            (0x212B, &[0x0041, 0x030A]),
            (0x1E9B, &[0x0073, 0x0307]),
            (0x1E69, &[0x0073, 0x0323, 0x0307]),
            (0x01C4, &[0x0044, 0x005A, 0x030C]),
            (0xFB01, &[0x0066, 0x0069]),
            (0x2139, &[0x0069]),
            (0x00A0, &[0x0020]),
            (0xFFA0, &[0x1160]),
            (0x1F213, &[0x30C6, 0x3099]),
            (0x00BD, &[0x0031, 0x2044, 0x0032]),
        ];
        for (cp, mapping) in expected {
            assert_eq!(
                decomposition(ch(cp)),
                Some(&chars_of(mapping)[..]),
                "U+{cp:04X}"
            );
        }
        let fdfa = decomposition('\u{FDFA}').expect("U+FDFA decomposes");
        assert_eq!(fdfa.len(), 18);
        assert_eq!(fdfa[..4], chars_of(&[0x0635, 0x0644, 0x0649, 0x0020])[..]);
        for cp in [0x0041, 0x0020, 0x4E00] {
            assert_eq!(decomposition(ch(cp)), None, "U+{cp:04X}");
        }
    }

    /// Assert-only: the same fact is the build-time gate G6, and no
    /// mutation of the committed data can paint it red without
    /// fabricating UCD lines.
    #[test]
    fn hangul_is_left_to_arithmetic() {
        assert_eq!(decomposition('\u{AC00}'), None);
        assert_eq!(decomposition('\u{D7A3}'), None);
        assert_eq!(compose('\u{1100}', '\u{1161}'), None);
        assert_eq!(compose('\u{AC00}', '\u{11A8}'), None);
        for c in chars() {
            if let Some(expansion) = decomposition(c) {
                assert!(
                    !expansion
                        .iter()
                        .any(|&part| ('\u{AC00}'..='\u{D7A3}').contains(&part)),
                    "the decomposition of U+{:04X} holds a Hangul syllable",
                    u32::from(c)
                );
            }
        }
    }

    #[test]
    fn combining_classes_are_read() {
        for (cp, class) in [
            (0x0301, 230),
            (0x0300, 230),
            (0x0323, 220),
            (0x05B0, 10),
            (0x093C, 7),
            (0x3099, 8),
            (0x0345, 240),
            (0x1D165, 216),
            (0x0F71, 129),
            (0x0041, 0),
            (0x10_FFFF, 0),
        ] {
            assert_eq!(ccc(ch(cp)), class, "U+{cp:04X}");
        }
    }

    #[test]
    fn primary_composites_compose_and_excluded_ones_do_not() {
        for (first, second, composite) in [
            (0x0041, 0x030A, 0x00C5),
            (0x0065, 0x0301, 0x00E9),
            (0x0049, 0x0307, 0x0130),
            (0x03B9, 0x0308, 0x03CA),
            (0x0B47, 0x0B3E, 0x0B4B),
            (0x30C6, 0x3099, 0x30C7),
        ] {
            assert_eq!(
                compose(ch(first), ch(second)),
                Some(ch(composite)),
                "U+{first:04X} U+{second:04X}"
            );
        }
        for (first, second) in [
            (0x0915, 0x093C),
            (0x2ADD, 0x0338),
            (0x0F71, 0x0F72),
            (0x0041, 0x0041),
        ] {
            assert_eq!(
                compose(ch(first), ch(second)),
                None,
                "U+{first:04X} U+{second:04X}"
            );
        }
    }

    #[test]
    fn composition_is_every_canonical_pair_minus_the_exclusions() {
        let excluded = listed(DERIVED_NORMALIZATION, "Full_Composition_Exclusion");
        let mut pairs = std::collections::BTreeMap::new();
        for line in UNICODE_DATA.lines() {
            let fields: Vec<&str> = line.split(';').collect();
            let mapping = fields[5];
            if mapping.is_empty() || mapping.starts_with('<') {
                continue;
            }
            let parts: Vec<u32> = mapping.split(' ').map(hex).collect();
            if let [first, second] = parts[..] {
                pairs.insert(hex(fields[0]), (first, second));
            }
        }
        for (&composite, &(first, second)) in &pairs {
            let expected = (!excluded[composite as usize]).then(|| ch(composite));
            assert_eq!(
                compose(ch(first), ch(second)),
                expected,
                "U+{composite:04X}"
            );
        }
        for &((first, second), composite) in COMPOSITION {
            let composite = u32::from(composite);
            assert_eq!(
                pairs.get(&composite),
                Some(&(first, second)),
                "U+{composite:04X}"
            );
            assert!(
                !excluded[composite as usize],
                "U+{composite:04X} is excluded"
            );
        }
    }

    #[test]
    fn confusable_sources_map_to_their_skeleton() {
        for (source, skeleton) in [
            (0x0430, 0x0061),
            (0x0410, 0x0041),
            (0x0435, 0x0065),
            (0x043E, 0x006F),
            (0x0440, 0x0070),
            (0x0441, 0x0063),
            (0x0445, 0x0078),
            (0x0455, 0x0073),
            (0x0456, 0x0069),
            (0x0391, 0x0041),
            (0x03B1, 0x0061),
            (0x03BF, 0x006F),
            (0xFF41, 0x0061),
            (0x0049, 0x006C),
            (0x0417, 0x0033),
        ] {
            assert_eq!(
                confusable_target(ch(source)),
                Some(ch(skeleton)),
                "U+{source:04X}"
            );
        }
    }

    #[test]
    fn only_letters_of_latin_cyrillic_or_greek_are_sources() {
        for cp in [
            0x0031, 0x217C, 0x4E00, 0x0BE6, 0x0181, 0x0061, 0x006C, 0x0436, 0xFF89, 0xFFA1, 0xFFB7,
        ] {
            assert_eq!(confusable_target(ch(cp)), None, "U+{cp:04X}");
        }
        assert_eq!(confusable_target('\u{FF41}'), Some('a'));
    }

    #[test]
    fn the_reverse_index_holds_every_twin_and_the_prototype() {
        let expected: [(u32, Script, &[u32]); 10] = [
            (0x0061, Script::Cyrillic, &[0x0430]),
            (0x0061, Script::Greek, &[0x03B1]),
            (
                0x0061,
                Script::Latin,
                &[0x0061, 0x0251, 0xAB64, 0xFF41, 0x1DF5A],
            ),
            (0x006F, Script::Greek, &[0x03BF, 0x03C3]),
            (0x006F, Script::Cyrillic, &[0x043E, 0x1C82]),
            (0x0063, Script::Greek, &[0x03F2]),
            (0x0033, Script::Cyrillic, &[0x0417, 0x04E0]),
            (0x006F, Script::Hangul, &[]),
            (0x0061, Script::Han, &[]),
            (0x0436, Script::Cyrillic, &[]),
        ];
        for (target, script, members) in expected {
            assert_eq!(
                confusables_with(ch(target), script),
                &chars_of(members)[..],
                "U+{target:04X} in {script:?}"
            );
        }
    }

    #[test]
    fn every_reverse_entry_maps_back_to_its_target() {
        let mut seen = std::collections::BTreeSet::new();
        for &(target, script, members) in CONFUSABLE_REVERSE {
            assert!(
                matches!(script, Script::Latin | Script::Cyrillic | Script::Greek),
                "U+{target:04X} in {script:?}"
            );
            assert!(
                seen.insert((target, script.as_str())),
                "U+{target:04X} in {script:?} twice"
            );
            assert!(!members.is_empty(), "U+{target:04X} in {script:?} is empty");
            assert!(
                members.windows(2).all(|pair| pair[0] < pair[1]),
                "ascending"
            );
            for &member in members {
                let at = format!("U+{:04X} under U+{target:04X}", u32::from(member));
                assert_eq!(
                    u32::from(confusable_target(member).unwrap_or(member)),
                    target,
                    "{at}"
                );
                assert_eq!(script_of(member), script, "{at}");
                assert!(is_letter(member), "{at}");
            }
        }
    }
}
